### ISSUE TITLE
Installed but not found

### ISSUE THREAD

**Issue by moaojarco** [kraanzu/dooit#1]
I installed dooit but when i use the command "doit/dooit" appears "**command not found: doit**"

**Comment by kraanzu** [comment]
Hey there! Sorry for the inconvenience. I thought to change the name as it was very common.
You should first uninstall doit using `pip uninstall doit` and then try to re-install.. It should work just fine  then...Lemme know if you need any other help

**Comment by moaojarco** [comment]
It was missing to export the PATH on linux and now it's working. Thanks!

**Comment by Aquarius-17** [comment]
can this be used in windows?
After i clone the depository ,i don't know what to do next,please help !

**Comment by kraanzu** [comment]
Hi @Aquarius-17 , 
there are steps mentioned in the README
after cloning you need to go into the cloned directory and run:
```
pip install .
```

This should install it for ya :)

**Comment by Aquarius-17** [comment]
Hey! @kraanzu ,thank you for your reply!!!  i do the command `pip install .` and it comes an exe called dooit.exe,I add the path of this exe to PATH so i can use the command`dooit` in cmd. But after i open the exe, i can see nothing but a black window,could you please help me ?

**Comment by kraanzu** [comment]
>  I can see nothing but a black window

Did it open in the terminal or as a separate standalone app?

**Comment by Aquarius-17** [comment]
> 

in the terminal，like this.
![QQ图片20220815145236](https://user-images.githubusercontent.com/88447561/184589610-40f8700c-1209-43e1-b289-05ac497a2986.png)

**Comment by kraanzu** [comment]
Hmm... I have no idea why that is happening.
I'll have to do a bit of research.
Will let you know if I get a lead :)

**Comment by Aquarius-17** [comment]
> 

thanks!!
