### ISSUE TITLE
[BUG] Reduce spacing before the blinking cursor.

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#105]
The extra spacing before the cursor is easily confused with space. I sometimes type thinking that there is a space but there is often no space.

![image](https://user-images.githubusercontent.com/270991/225988053-e85770a4-55a3-403e-ba4f-4047f2fa32ee.png)

**Comment by kraanzu** [comment]
That is not a cursor but rather the pipe `|` symbol.
So the max I can do is this:

![image](https://user-images.githubusercontent.com/97718086/226081732-6917a794-7693-4156-b3ae-29bbf3f45e33.png)

But I'm thinking of moving to background highlighted cursor which would totally eliminate the caret problems :D

**Comment by sathishmanohar** [comment]
Can this unicode symbol `⎸` work instead of the pipe symbol `|`

https://www.compart.com/en/unicode/U+23B8

**Comment by kraanzu** [comment]
I guess I'll use background highlight which was the plan anyways
I'll keep this thread open :)

**Comment by sathishmanohar** [comment]
Even with background highlighting there will be one character space between two characters while editing. It feels like a hack than a solution. I suggest we do down the route of implementing an actual cursor while editing text.

**Comment by kraanzu** [comment]
> I suggest we do down the route of implementing an actual cursor while editing text.

Already tried! Wasn't able to find a solution

> Even with background highlighting there will be one character space between two characters while editing.

No I mean a cursor like vim's NORMAL mode
Something like this:

![image](https://user-images.githubusercontent.com/97718086/226173609-a95e0b17-aa24-4cc1-a634-734b462c0998.png)
