### ISSUE TITLE
[BUG] < and > symbols disappear after restart

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#107]
I have a description like this

![image](https://user-images.githubusercontent.com/270991/226292216-52ff7503-377c-4192-8fc7-726ebf0d7297.png)

Once I restart dooit, it becomes like this. `<` and `>` just disappears

![image](https://user-images.githubusercontent.com/270991/226292548-00841664-dc20-40a6-93c6-74ac680fa32c.png)

**Comment by kraanzu** [comment]
Wow this is a strange one! I'll look into it!
Thanks!

**Comment by V1ad0S** [comment]
Oh... :(
![Screenshot from 2023-04-21 16-21-17](https://user-images.githubusercontent.com/48799803/233646944-f2d551f9-a331-4cff-b528-b682c21fd5f7.png)

![Screenshot from 2023-04-21 16-22-20](https://user-images.githubusercontent.com/48799803/233647082-f8bfafe5-6116-4a5a-a1dc-25e51fb702b5.png)

**Comment by kraanzu** [comment]
Damn, that's a nasty bug!
 I'm thinking of moving to a different format instead of the todo.txt I'm doing now. This app is too complex for that :(

Thanks @V1ad0S for the examples! :dagger:
