### ISSUE TITLE
[FEAT] Make link clickable/openable

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#108]
I have a link in a description. When I click on the link I expect the link to open in my default browser but as of now nothing is happening.

The link is detected and underlined. The cursor changes to link click cursor but on click nothing happens.

**Comment by kraanzu** [comment]
Hmmm... Didn't add the feature but can do

**Comment by Justinzobel** [comment]
Sounds more like an issue with the terminal. I use Konsole by KDE and I have the option to click links when holding CTRL.

**Comment by sathishmanohar** [comment]
I confirm ctrl+click works on a few terminals and it doesn't work on kitty. Is there a way to make the behavior more uniform/predictable across terminals.

**Comment by kraanzu** [comment]
> Is there a way to make the behavior more uniform/predictable across terminals.

Yes If I can use a proper regex to determine URLs then I make it clickable I suppose :D

**Comment by kyeboard** [comment]
> I confirm ctrl+click works on a few terminals and it doesn't work on kitty. Is there a way to make the behavior more uniform/predictable across terminals.

Try **just** clicking it instead of pressing ctrl. I just tested on my pc and urls open if i just click.... however it doesnt if i alongside press ctrl
