### ISSUE TITLE
[BUG] Unable to launch the application (python 3.9)

### ISSUE THREAD

**Issue by qubistt** [kraanzu/dooit#109]
**Describe the bug** 🐛
When I go to my `~/.local/bin` and run `./dooit`, the app throws a TypeError

**To Reproduce** 🐣
1. Launch the app using `./dooit`
2. Python version in 3.9
3. See error
4. `
File home/qubist/.local/lib/python3.9/site-packages/dooit/ui/widgets/sort_options-py",line23,inSortOptions
name: str I None = None,
TypeError: unsupported operand type(s) for I: 'type and 'NoneType
`

**Expected behavior**  🤔 
The app should launch

**Screenshots** 🧐
No desktop environment currently, so here’s a photo of my screen
![41B0075B-DCBE-45FD-8CB2-93A3C51432E5](https://user-images.githubusercontent.com/78350166/227937665-77dc1b10-4926-4e50-b770-38a92f8e722c.jpeg)

**Desktop (please complete the following information):**  🤖
 - OS: Raspberry Pi OS Lite (cli only)
 - Version: Debian GNU/Linux 11

**Additional context** 📝
First time using this app,

**Comment by qubistt** [comment]
There could be mistakes in the error in point four since I typed it out myself

**Comment by kraanzu** [comment]
I hope the issue was fixed! WIll close this as of now
Feel free to re-open if anything comes up
