### ISSUE TITLE
[BUG] Font Icons not displayed Correctly

### ISSUE THREAD

**Issue by shashidharybhat** [kraanzu/dooit#110]
**Describe the bug** 🐛
Dooit fails to display the icons for urgency, due and tags despite the use of Nerd Fonts in the terminal emulator.

**Expected behavior**  🤔 
Alacritty can render these fonts as seen in the 2nd screenshot. 

**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/23742213/228475576-b11fac7c-9041-4c44-8543-0c76be3d4c75.png)
![image](https://user-images.githubusercontent.com/23742213/228475756-47d37626-8c83-4bc5-b1d8-0f032f2647ff.png)

**Attempts to resolve**
1. Tried to flush font cache with `fc-cache`
2. Moved Fonts from `/usr/local/share/fonts` to `.fonts/` too
3. Replicated the alacritty config from Owner's dotfiles.

**Desktop (please complete the following information):**  🤖
 - OS: Debian 11 Stable 
 - Version Dooit-1.0.1

**Comment by shashidharybhat** [comment]
Icons work in the description but not in the Columns.
![image](https://user-images.githubusercontent.com/23742213/228576204-7372e12a-f992-44e7-80cd-e91ba23f7a74.png)

**Comment by kraanzu** [comment]
> Icons work in the description but not in the Columns.

This is super strange!
So you are using both my dooit's and alacritty's config?

**Comment by shashidharybhat** [comment]
I realized that the dooit config had been purged by mistake. After restoring it, the icons load properly. 
I suggest a default config dooit falls back onto in case of missing dotfiles.
