### ISSUE TITLE
💡 [FEAT] Clear due date when selected

### ISSUE THREAD

**Issue by shashidharybhat** [kraanzu/dooit#111]
**Is your feature request related to a problem? 😢 Please describe.** 
While editing the due date, it is by default set to `none`. I have to manually remove it to add in a new due date.
Having to clear the due date for every task takes little time, but over a period it adds up.

**Describe the solution you'd like**   🤔
It would be better if it was cleared when entering to ease the process of adding a due date.

**Describe alternatives you've considered**  🧐
I would love to implement this feature but I'm currently strapped for time. So it's just an issue for now.

**Comment by kraanzu** [comment]
Hi again @shashidharybhat !

>  It would be better if it was cleared when entering to ease the process of adding a due date.

Hmm...I was already thinking of adding keybindings for editing ( which is current behaviour ) vs changing ( which means the typing area will be cleared before you write anything)

>  I would love to implement this feature but I'm currently strapped for time. So it's just an issue for now.

haha... I'm also really busy but I'll be back within a week! :muscle: 

 @kyeboard Would you like to work on this issue?

**Comment by kyeboard** [comment]
Sure :)
