### ISSUE TITLE
Dooit does not handle numbers at all. If you have two TODOs -- `Foo 1` and `Foo 2`, subsqeqeunt reloads of the app will merge the TODOs into just `Foo`.

### ISSUE THREAD

**Issue by j-barnak** [kraanzu/dooit#112]
**Describe the bug** 🐛
Dooit does not handle numbers at all. If you have two TODOs -- `Foo 1` and `Foo 2`, subsqeqeunt reloads of the app will merge the TODOs into just `Foo`.

**To Reproduce** 🐣
Add `TODO 1` and `TODO 2` as items using `a`. Quit and reload app.

**Expected behavior**  🤔 
I expect two TODOs: `TODO 1` and `TODO 2`

**Comment by kraanzu** [comment]
Thanks @j-barnak for opening the issue. 
Working on this!

**Comment by kraanzu** [comment]
Fixed! Can you check by installing the latest version?

```
python -m pip install git+https://github.com/kraanzu/dooit.git
```

Thanks :D

**Comment by j-barnak** [comment]
Yep, this fixed it!
