### ISSUE TITLE
💡 [FEAT] Duplicate Items/Todo Lists

### ISSUE THREAD

**Issue by tsids** [kraanzu/dooit#113]
**Describe the solution you'd like**   🤔
I think it would be useful if you could duplicate individual items, or maybe even entire todo lists.

**Comment by kraanzu** [comment]
Hey @tsids , not sure how todos with the same description are helpful?

**Comment by tsids** [comment]
It can be useful for someone who wants to create a new todo list quickly without having to manually copy and paste each item, since it's easier to make changes to a duplicated task/list instead of making one from scratch.

It's also useful for someone who is using a workspace as a template as they can duplicate the entire workspace or specific tasks, and change whatever they want to change.

**Comment by kraanzu** [comment]
I see. Creating a template is a really good use case. I am moving to a different method of saving tasks which would actually allow duplicates. Thanks for the explanation :D
