### ISSUE TITLE
💡 [FEAT] Toggle switch between displaying the due date of ToDos as target date or remaining time

### ISSUE THREAD

**Issue by voxcon** [kraanzu/dooit#116]
**Is your feature request related to a problem? Please describe.** 
There is no problem, but it would come in handy to be able to toggle switch between showing the due date as target date or showing it as time remaining. 

**Describe the solution you'd like**  
By default the due date of your ToDos should be displayed as is, e.g.:

`- do A                              11 March 10:00`

By using a keybind, e.g. "v" users should be able to switch the due date to show the remaining time, e.g:

`- do A                              2 days 5 hours 34 mins`
 
**Describe alternatives you've considered** 
None.

**Comment by kraanzu** [comment]
I was actually planning something like that!

Not even time but let's say you have a todo which you are supposed to complete on the 10th of May ( Today's 9th ), then it would automatically turn into, let's say, tomorrow

Similarly, the one which was due on the 8th will have "Yesterday"
