### ISSUE TITLE
💡 [FEAT] Add location of todo.yaml to wiki

### ISSUE THREAD

**Issue by Justinzobel** [kraanzu/dooit#120]
I had to use find to find it in my filesystem at ~/.local/share/dooit/todo.yaml

**Comment by kraanzu** [comment]
I see... I thought it was already done but realized that it was only for the config location! I will do that.
I'm not sure if everything is appropriately documented so I you find any other part missing/confusing, do open an issue!
Thank you!

**Comment by kyeboard** [comment]
Hey Justinzobel, turns out it was already there in the wiki (https://github.com/kraanzu/dooit/wiki/API#manager-class). Therefore im closing this issue.

Have a happy time with dooit!

**Comment by Justinzobel** [comment]
Under the API section. Not somewhere I'd even consider looking. Any chance it can be placed in a more obvious location as well?

**Comment by kraanzu** [comment]
Yes might as well do that! @kyeboard can you place it just below config location section?

**Comment by kraanzu** [comment]
Hey @Justinzobel, it's in the home section now!

**Comment by Justinzobel** [comment]
Many thanks!
