### ISSUE TITLE
💡 [FEAT] Option to move completed tasks to the bottom

### ISSUE THREAD

**Issue by Justinzobel** [kraanzu/dooit#121]
**Describe the solution you'd like**   🤔
I'd like to be able to configure dooit to move items to the bottom of the list once marked as completed.

**Describe alternatives you've considered**  🧐
An alternative would be a keyboard toggle to hide completed items.

**Comment by kraanzu** [comment]
Hey @Justinzobel , you might wanna check out this thread #115 and see if you want something similar :D
I'll this one as duplicate
