### ISSUE TITLE
[BUG] Can't use up or down arrow keys to scroll help page

### ISSUE THREAD

**Issue by Justinzobel** [kraanzu/dooit#122]
**Describe the bug** 🐛
I can't use the up or down arrow keys to scroll the help page

**Expected behavior**  🤔 
Able to use up/down arrows like in regular pages

**Desktop (please complete the following information):**  🤖
 - OS: Fedora 38 KDE
 - dooit Version 1.0.1

**Comment by kraanzu** [comment]
Wow didn't notice it. Maybe I need to set some different CSS properties

Although I tried the installing dooit from the dev branch and it's working fine! I will merge it by this weekend!

**Comment by Justinzobel** [comment]
Awesome, looking forward to it. I will try and package dooit for Feodra at some point so I have easy updates instead of using pip.

**Comment by kraanzu** [comment]
Oh, Fedora also has a community-based package manager? I only knew about `dnf`. Thanks man!
What's it called?

**Comment by Justinzobel** [comment]
I am a packager for Fedora so I can submit things to the repository. But initially I'll just get it built in a Copr which is basically a community build area for Fedora.

**Comment by kraanzu** [comment]
Oh cool! Thank you. Just wait a bit longer for the new release!

**Comment by kraanzu** [comment]
Fixed!
