### ISSUE TITLE
[BUG] Documentation mentions DASHBOARD, while it should be dashboard

### ISSUE THREAD

**Issue by FelixKratz** [kraanzu/dooit#123]
Hi there,
first of all thanks for the awesome update to v1! I am currently migrating and am super impressed by the new features.

I have found that the documentation states that the variable for the dashboard is `DASHBOARD` (https://github.com/kraanzu/dooit/wiki/Configuration#dashboard), however it really should be `dashboard`, as seen in the default_config. 

Additionally, the example shows
```python
ART = some_ascii_art
QOUTE = some_qoute
STATS = [
     f"Completed: {completed}",
     f"Pending: {pending}",
     f"Overdue: {overdue}",
]
PAD = " "
DASHBOARD = [ART, QOUTE, PAD, STATS]
```
but it is not a priori clear how to acquire the variables `completed`, `pending` and `overdue`, making the onboarding a bit frustrating.

**Comment by kraanzu** [comment]
> I am currently migrating and am super impressed by the new features.

Thank you so much @FelixKratz !

My bad!!!! I'll fix this.


> but it is not a priori clear how to acquire the variables completed, pending, and overdue, making the onboarding a bit frustrating.

Yep, I'm working on it to make a better starting config that would be present at the default location!

**Comment by FelixKratz** [comment]
I have since managed to get the dashboard running:
![Screenshot 2023-05-28 at 12 07 07](https://github.com/kraanzu/dooit/assets/22680421/9ff0bf2f-6c0d-400f-b688-a995358a1393)

Again, great work!

**Comment by kraanzu** [comment]
Damn, that looks coooollll!

This made my day. Thanks @FelixKratz !

**Comment by kraanzu** [comment]
I'll make it much easier to get those numbers
Note: In the README images you might see the numbers in the status bar which are getting refreshed constantly, I noticed that it might result in a slow response time of the app which will be fixed in the next release

**Comment by kraanzu** [comment]
Also, the `University` Workspace which you made is getting warped by an ellipsis (...)
This will be changed in the next release too!

**Comment by satishjasthi** [comment]
@kraanzu , Big thanks for creating this awesome app! 🎉 Love it! I have a question about the dashboard. Not sure how to configure it to quickly see my todo list state. 🤔 Any tips on that?

**Comment by kraanzu** [comment]
> Big thanks for creating this awesome app! 

Thanks a lot @satishjasthi! Really glad to hear that!

> configure it to quickly see my todo list state.

Do you mean info about completed/pending/overdue tasks?

> Also is there a way to copy paste dates and tags, because every time typing entire date time

This will be implemented in the next release! ( which should be in a few days)

**Comment by satishjasthi** [comment]
Yes, oh nice, will be eagerly waiting for the next release.

**Comment by danieledipompeo** [comment]
@FelixKratz could you share your setup/basic_config file?

I'm stuck on how to find the following variables:

```python
STATS = [                                                                                                                                
     f"Completed: {completed}",
     f"Pending: {pending}",
     f"Overdue: {overdue}",
]
```

and I like your dashboard message ;)

**Comment by FelixKratz** [comment]
> @FelixKratz could you share your setup/basic_config file?
> 
> I'm stuck on how to find the following variables:
> 
> ```python
> STATS = [                                                                                                                                
>      f"Completed: {completed}",
>      f"Pending: {pending}",
>      f"Overdue: {overdue}",
> ]
> ```
> 
> and I like your dashboard message ;)

Sure, I have added them to my dotfiles: https://github.com/FelixKratz/dotfiles/tree/master/.config/dooit

**Comment by kraanzu** [comment]
Awesome config @FelixKratz ! Really happy to see that.
Refreshing might slow down the app but there's a fix in the dev branch. 

The development stopped because my motherboard is dead T_T. Will push updates soon!

**Comment by pizdjuk** [comment]
@FelixKratz deleted his config. And I was not able to understand how to get the variables completed, overdue and pending.

**Comment by kraanzu** [comment]
Hi @pizdjuk, [Here](https://github.com/kraanzu/.dotfiles/tree/main/configs/dooit) is my config

[Here](https://github.com/kraanzu/.dotfiles/blob/429a100d0db95e86093a0a8c34ec0a785047a1ea/configs/dooit/utils/funcs.py#L32) is the util func

**Comment by pizdjuk** [comment]
Yuhu! Thx a lot! Now it works and looks cool. It would be nice to provide this as default config, because the default config looks not as in screenshots in README.md
