### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrMic** [kraanzu/dooit#124]
**Describe the bug** 🐛
Due date format: dd-mm-yyyy is not recognized

**To Reproduce** 🐣
Press "d" and enter the date: dd-mm-yyyy

**Expected behavior**  🤔 
The date of the day appears instead of "none" ...

With Linux

The message at the bottom left is: "Cannot parse the string"

**Comment by kraanzu** [comment]
Hey @MrMic ,
That is very odd, I tried it and the string was parsed in my case! 
You can also type in a common language like 1 Jan, today, tomorrow, etc!

**Comment by kraanzu** [comment]
Closing as stale and not verified. Feel free to re-open if the issue still persists
