### ISSUE TITLE
[BUG] Wrong characters for icons.

### ISSUE THREAD

**Issue by empik002** [kraanzu/dooit#13]
On Linux Pop_os! 21.10 in Kitty terminal emulator (and Gnome terminal as well) the icons next to Menu and Todos are different than those in the demo video (chinese, russian characters and such) 

It is entirely possible that my configuration is the issue. If that is the case could I get some pointers on how to fix the issue myself?

**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/34795617/174517944-ccf89ed4-823f-47aa-b616-cf0b5ae676d6.png)
![image](https://user-images.githubusercontent.com/34795617/174517977-1a5776d5-0607-4258-a3ce-a315aef08c56.png)

**Comment by kraanzu** [comment]
Hey there! By default I am using [Nerd Fonts](https://www.nerdfonts.com/) as most people use that.
You can either use a nerd font or change icons in your `~/.config/dooit/config.yaml` file

**Comment by empik002** [comment]
Great, thanks. Might want to state that in the readme. to avoid more issues like this. (both how to change them and the Nerd Fonts)
