### ISSUE TITLE
[BUG] Priority labels are the wrong way around

### ISSUE THREAD

**Issue by jaackflower** [kraanzu/dooit#133]
**Describe the bug** 🐛
When I hit the plus key it goes down the list to D instead of up to A.  It also sorts them as if D is the highest priority.

**To Reproduce** 🐣
Press plus on the task.
Sort by urgency.

**Expected behavior**  🤔 
Plus increases the urgency to A.

**Desktop (please complete the following information):**  🤖
 - OS: MacOS 12.5.1

**Comment by kraanzu** [comment]
If it's a visual problem, then you can change it inside of config:

```python
TODO = {
    "urgency1_icon": "🅐",
    "urgency2_icon": "🅑",
    "urgency3_icon": "🅒",
    "urgency4_icon": "🅓",
}
```

This is from default config, you can just reverse the order :wink:

**Comment by kraanzu** [comment]
Closing this Issue. Feel free to re-open in case of any queries
