### ISSUE TITLE
[BUG] Config file doesn't change colours.

### ISSUE THREAD

**Issue by jaackflower** [kraanzu/dooit#134]
**Describe the bug** 🐛
Not sure if I'm just being stupid here, but whenever I try to edit the config.yaml file, it doesn't actually change the colours. If anyone could write a step by step on how to do it, that'd be appreciated!

**Desktop (please complete the following information):**  🤖
 - OS: MacOS 12.5.1

**Comment by kraanzu** [comment]
Hey @jaackflower , can you upload the config or share the code snippet which you're trying?

**Comment by jaackflower** [comment]
I fixed it don't worry, I was editing the wrong file! My bad!
