### ISSUE TITLE
[BUG] My version shows as 1.0.1 after installing from AUR

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#139]
**Expected behavior**  🤔 
Expected to get 2.0 with latest features

**Desktop (please complete the following information):**  🤖
 - OS: Arch Linux

**Comment by kraanzu** [comment]
Hey! Thanks for bringing this to my attention!
I'll try to fix it ASAP. But there's more problem.
One of the packages used is not on AUR (it's under python2) + the main TUI package is not updated as well.
I'd recommend using something like [pipx](https://pypa.github.io/pipx/) for now

**Comment by kraanzu** [comment]
Closing because this package works!
AUR: https://aur.archlinux.org/packages/dooit
