### ISSUE TITLE
[BUG] Ctrl-q do NOT quit the App

### ISSUE THREAD

**Issue by MrMic** [kraanzu/dooit#140]
**Describe the bug** 🐛
Ctrl-q do NOT quit the App

**To Reproduce** 🐣
Ctrl-q

**Expected behavior**  🤔 
Quit the App

**Desktop (please complete the following information):**  🤖
 -  Linux
 - Version 2.0.0

**Comment by kraanzu** [comment]
Oops! My bad. Gimme a few minutes!

**Comment by MrMic** [comment]
No problem. Take your time!
Moreover, the date format must be written like this: MM-dd-YYYY instead 
of: mm-DD-YYYY like in the docs ...

**Comment by kraanzu** [comment]
Alright, this should be fixed now!

As for the date and time stuff,
You can now set a variable in your config file called `USE_DAY_FIRST`

Example:

```python
USE_DAY_FIRST = True
```


By default, it's set to `True` which means that it'll parse in mm-dd format
So when you type `1-10` this means `1st of October`
But if the variable is set to False, it'll mean `10th of January`

**Comment by kraanzu** [comment]
Closing as fixed
Feel free to re-open if there's any issue

**Comment by MrMic** [comment]
No! Still not working. Can't quit the App 😥

**Comment by kraanzu** [comment]
Hey!
It looks like PyPi has some extra authentication stuff that prevented from publishing

You can install the latest version using this command:

```sh
pip install git+https://github.com/kraanzu/dooit.git
```
