### ISSUE TITLE
💡 [FEAT] Support ISO_8601 (YYYY-MM-DD)

### ISSUE THREAD

**Issue by samlevesque** [kraanzu/dooit#141]
**Is your feature request related to a problem? 😢 Please describe.** 
I can't use the international standard for date: https://en.wikipedia.org/wiki/ISO_8601

**Describe the solution you'd like**   🤔
Support for a date format that makes sense

**Describe alternatives you've considered**  🧐
Nothing cause I won't use this tool without it

**Additional context** 📝
YYYY-MM-DD
It's easy.
It's unambiguous.
It sorts itself.

**Comment by kraanzu** [comment]
Hi @samlevesque,
Do you mean setting or displaying?

**Comment by samlevesque** [comment]
Both, I'ld like to be able to type 2023-09-16 and have it show as 2023-09-16

**Comment by kraanzu** [comment]
Hmm...sounds good. I'll add a setting variable so you can customize this behavior!

**Comment by samlevesque** [comment]
That would be awesome thank you !
