### ISSUE TITLE
[BUG] Opaque background on transparent terminals

### ISSUE THREAD

**Issue by SuperDuperDeou** [kraanzu/dooit#144]
**Describe the bug** 🐛
If Dooit is run on a terminal with a (semi-)transparent background, instead if respecting the transparency, Dooit will draw the background as completely opaque.

**To Reproduce** 🐣
1. Install a terminal that supports transparency (ex. St with alpha patch, Kitty, Alacritty).
2. Set an non-zero transparency.
3. Run Dooit on that terminal.

**Expected behavior**  🤔 
A curses application should respect the transparency of the terminal, so, if the terminal is semi-transparent, so should be the background drawn by the curses application. (Look programs such as Less, Vim, and Nano for reference.)

**Screenshots** 🧐
![dooit](https://github.com/kraanzu/dooit/assets/87223140/cfd3f597-7ff5-422e-bb5d-d059c32b9465)

**Desktop (please complete the following information):**  🤖
 - OS: Artix GNU/Linux
 - Version: Supposedly any (tested 2.0.0 and 2.0.1)

**Additional context** 📝

**Comment by kraanzu** [comment]
Hey @SuperDuperDeou!

Unfortunately this was done intentionally by the TUI framework which dooit is based on :(
[Check out this](https://textual.textualize.io/FAQ/#how-can-i-set-a-translucent-app-background) for more details
