### ISSUE TITLE
[BUG] unable to launch after installing via pip

### ISSUE THREAD

**Issue by Clumsy-Coder** [kraanzu/dooit#145]
**Describe the bug** 🐛
Dooit fails to launch after installing via pip

**To Reproduce** 🐣
1. run command `pip install dooit`
2. run `dooit`
3. See error

**Expected behavior**  🤔 
to launch dooit

**Screenshots** 🧐

![image](https://github.com/kraanzu/dooit/assets/19594044/75998c9b-905b-4bf4-9319-0d6509259f49)

**Desktop (please complete the following information):**  🤖
 - OS: MacOS 10.15.7
 - Version 2.0.0

**Additional context** 📝
- python added to path `export PATH="$HOME/Library/Python/3.8/bin:$PATH"`
- `which dooit` : `/Users/umar/Library/Python/3.8/bin/dooit`
- python version: `2.7.16`
- python3 version: `3.11.5`

**Comment by Clumsy-Coder** [comment]
I was able to launch on dooit version 1.0.1

```bash
pip3 install --force-reinstall dooit==1.0.1
```

**Comment by kraanzu** [comment]
Hey @Clumsy-Coder !

That's weird. 
Can you run this instead and check:

```bash
python3 -m pip install dooit
```

**Comment by xzdlj** [comment]
Hi @Clumsy-Coder 
Judging from the `.../Python/3.8/bin`, it seems that you are using python 3.8. And the `|` was introduced in python 3.10([bpo-41428](https://bugs.python.org/issue?@action=redirect&bpo=41428)), so try to check the python version.

**Comment by kraanzu** [comment]
> Python/3.8

Oh yes totally missed that. Thanks for mentioning this @xzdlj 
Yes that seems to be the issue

**Comment by kraanzu** [comment]
Pushed a fix!

Can do a pip install using this @Clumsy-Coder 

```bash
python3 -m pip install git+https://github.com/kraanzu/dooit.git
```
