### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fallowmcolstein** [kraanzu/dooit#15]
**Describe the bug** 🐛
I just installed it using the one-liner command, and when I try to run it, it says some stuff and then ModuleNotFoundError: No module named 'yaml'

**To Reproduce** 🐣
run dooit

**Screenshots** 🧐
full output:
![image](https://user-images.githubusercontent.com/82470952/174537278-9828d444-6969-4bb9-86dc-4d1039e88fcd.png)

**Desktop (please complete the following information):**  🤖
 - OS: Windows
 - Version 11

**Comment by kraanzu** [comment]
Well that's strange... I thought `yaml` was included in std lib.
You can install `pyyaml` using `pip install pyyaml`
I'll update the dependecies
