### ISSUE TITLE
[BUG] Crash when trying to create a workspace in 3.8

### ISSUE THREAD

**Issue by trag1c** [kraanzu/dooit#167]
**To Reproduce** 🐣
1. Run `dooit` in Python 3.8
2. Try creating a workspace by pressing `a`
3. See error

**Desktop (please complete the following information):**  🤖
 - OS: macOS
 - Version: 14.2.1

**Additional context** 📝
Related issue: #161

The error seems to be caused by this snippet:
https://github.com/kraanzu/dooit/blob/b1ea93246494d33b3094786c3dbd2943805500a0/dooit/api/model.py#L79-L82
Stacking `@classmethod` on top of `@property` to get a class property is only supported in Python 3.9–3.10 (though it works in 3.11+ for now, see [the changes mentioned in the docs](https://docs.python.org/3.11/library/functions.html#classmethod)).

**Comment by kraanzu** [comment]
Ah I see now, one other person was having the same issue and I had no idea why #161
But when I told him to use the binary, it worked for him!

Thanks!

**Comment by trag1c** [comment]
Yes, I've mentioned that issue in the description here :+1:

You're welcome.
