### ISSUE TITLE
[BUG] Different colors from what has been configured.?

### ISSUE THREAD

**Issue by Hamadah2O2** [kraanzu/dooit#182]
**Describe the bug** 🐛
I just configured the color, but the color I set is different from what is displayed. 
It only happens on the st terminal, but it's normal on the Alacritty terminal.

**To Reproduce** 🐣
1. Using [Luke st](https://github.com/LukeSmithxyz/st)
2. run dooit
3. Looks different from what was configured.

**Screenshots** 🧐
On st:
![image](https://github.com/user-attachments/assets/3ea926bf-6b33-4bfc-a856-c86a3a86bc9d)

On Alacritty:
![image](https://github.com/user-attachments/assets/4f0ef97c-0b48-484a-8789-4b4c10d42089)

**Desktop:**  🤖
 - OS: Debian GNU/Linux 12 (bookworm) x86_64
 - Kernel: 6.1.0-22-amd64
 - Shell: zsh 5.9
 - Resolution: 1366x768
 - WM: i3
 - Theme: Flat-Remix-GTK-Bluez-Dark-Solid [GTK2/3]
 - Icons: Flat-Remix-Blue-Dark [GTK2/3]
 - Terminal: st
 - CPU: AMD E1-2100 APU (2) @ 1.000GHz (yes 🥲)
 - GPU: AMD ATI Radeon HD 8210

**My Configuration** 📝
config.py:
```python
black = "#30304a"
dark_black = "#343450"
white = "#e5e9f0"
grey = "#d8dee9"
red = "#bf616a"
frost_green = "#8fbcbb"
cyan = "#88c0d0"
green = "#a0e169"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
orange = "#d08770"

BACKGROUND = black 
BAR_BACKGROUND = black 
WORKSPACES_BACKGROUND = black 
TODOS_BACKGROUND = black 
# BORDER_DIM = grey + " 50%" 
# BORDER_LIT = blue 

BORDER_TITLE_DIM = grey, dark_black 

BORDER_TITLE_LIT = white, blue

SEARCH_COLOR = red 
YANK_COLOR = blue 
SAVE_ON_ESCAPE = False 
USE_DATE_FIRST = True 
```

Is it my terminal or else ?

**Comment by kraanzu** [comment]
Yes It's your terminal, (a particular setting actually), I tried with vanilla st config and it ran fine

I was not able to determine what caused this issue tho :(

**Comment by Hamadah2O2** [comment]
Sad to hear that, i just tried the vanilla st but still not working. Well it seems like I will just change the terminal emulator.  just doo it.
I don't know why every time there is a great application, there always seems to be some problem happen to me :)

BUT, IF I JUST STARTED THE ST USING ALACRITTY (eg: `alacritty -e st`) THE ST JUST SHOW THE TRUE COLORS FOR DOOIT, IT SEEMS LIKE SOMETHING IS HAPPENING WHEN ST IS JUST STARTED

.... Yeah, im just tired. just change the terminal an resolve the problem. just doo it.
I am fine, Thank you for answering me. this the best todo manager for me btw. 😄

**Comment by kraanzu** [comment]
Super glad to hear that. More nice stuff incomingggg!

**Comment by Hamadah2O2** [comment]
I just found the solution.
Just add `export COLORTERM=truecolor` to `.zshrc` or other shell config, and i am ready todooit 😆
