### ISSUE TITLE
💡 [FEAT] Configurable Todo List Column Order

### ISSUE THREAD

**Issue by silentjay** [kraanzu/dooit#185]
Would be nice option to be able to configure the column order in the todo list. For example being able to move the urgency and/or the date columns to the left of the task description/status icons would help in picking out tasks to work on for those of us using full screen terminals.

![2024-09-15_11-56 (1)](https://github.com/user-attachments/assets/ba190a62-f694-443b-b44d-374415c4a36a)

**Comment by kraanzu** [comment]
Do you mean [something like this](https://github.com/kraanzu/dooit/wiki/Configuration#todos)?

Check out the first line of the section

**Comment by silentjay** [comment]
Ah that's exactly what I meant thanks. I did check out the config but completely missed this setting sorry. Have now set it in my config and changed the order but there's no change in the order. Had a quick search in the code and there's no reference to `COLUMN_ORDER` so I assume it's not been implemented yet?

**Comment by silentjay** [comment]
No problem, I'll close this then. Once I'm more familiar with the app and codebase I might create some pull requests although maybe I'll wait for the new version first.
