### ISSUE TITLE
[BUG] Fail to open help menu

### ISSUE THREAD

**Issue by Shaun-F** [kraanzu/dooit#19]
**Describe the bug** 🐛
ctrl+p fails to open help menu

**To Reproduce** 🐣
1. open dooit
2. press ctrl+p
3. weep

**Expected behavior**  🤔 
help menu opens

**Desktop (please complete the following information):**  🤖
           /:-------------:\         
        :-------------------::        OS: Fedora 36 ThirtySix
      :-----------/shhOHbmp---:\      Kernel: x86_64 Linux 5.18.5-200.fc36.x86_64
    /-----------omMMMNNNMMD  ---:     Uptime: 7h 6m
   :-----------sMMMMNMNMP.    ---:    Packages: 6480
  :-----------:MMMdP-------    ---\   Shell: zsh 5.8.1
 ,------------:MMMd--------    ---:   Resolution: 1920x1080
 :------------:MMMd-------    .---:   DE: GNOME 42.2
 :----    oNMMMMMMMMMNho     .----:   WM: Mutter
 :--     .+shhhMMMmhhy++   .------/   WM Theme: 
 :-    -------:MMMd--------------:    GTK Theme: Adwaita [GTK2/3]
 :-   --------/MMMd-------------;     Icon Theme: Adwaita
 :-    ------/hMMMy------------:      Font: Cantarell 11
 :-- :dMNdhhdNMMNo------------;       Disk: 182G / 290G (65%)
 :---:sdNMMMMNds:------------:        CPU: AMD Ryzen 7 5700U with Radeon Graphics @ 16x 4.372GHz
 :------:://:-------------::          GPU: AMD RENOIR (LLVM 14.0.0, DRM 3.46, 5.18.5-200.fc36.x86_64)
 :---------------------://            RAM: 5196MiB / 9804MiB

**Additional context** 📝
esc key also fails to exit program

**Comment by kraanzu** [comment]
Hey there! The command "ctrl-p" was replaced with "?". See if that works!

**Comment by kraanzu** [comment]
Also, you can customize keybindings in the config file too :)
Happy todo!
