### ISSUE TITLE
Python versioning issue

### ISSUE THREAD

**Issue by taladan** [kraanzu/dooit#2]
Doit will not install with given instructions on python 3.8:

`Collecting git+https://github.com/kraanzu/dooit.git
  Cloning https://github.com/kraanzu/dooit.git to /tmp/pip-req-build-uoxtcydw
  Running command git clone -q https://github.com/kraanzu/dooit.git /tmp/pip-req-build-uoxtcydw
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package 'dooit-0.1.0' requires a different Python: 3.8.10 not in '>=3.10,<4.0'
`

**Comment by NiggoP** [comment]
You need Python 3.10 or greater

**Comment by kraanzu** [comment]
At this point all major distributions have upgraded to `python3.10` so I didn't focused to make it compatible with `python3.8`.
I am closing this issue for now

**Comment by grandchild** [comment]
That and the type hints:
 * `List[Dict[Tuple[...]]]` instead of `list[dict[tuple[...]]]`)
 * `Optional[str]` and `Union[str|int]` instead of `str | None` and `str | int` respectively
 
But awesome of you to restart supporting 3.8! ❤️

**Comment by grandchild** [comment]
Have a look at https://github.com/grandchild/dooit/commit/5bf81ad4e27898356b67fc2942a9c7054f665aa0 for the changes wrt your `main` (I understand you're working on a redesign, but maybe you can copy-paste one or two hunks from my patch. 🙂

**Comment by kraanzu** [comment]
Indeed. That's a lot of changes you did there!
I'm also changing the config file and stuff so things might be a bit different, but yeah, thanks for the work!
I really appreciate it! 😄
