### ISSUE TITLE
[BUG]Help page does not appear

### ISSUE THREAD

**Issue by vitoindelicato** [kraanzu/dooit#20]
**Describe the bug** 🐛
ctrl+p does not open help page

**To Reproduce** 🐣
1. Install 
2. Run
3. Type ctrl+p
4. Nothing happen

**Expected behavior**  🤔 
Help page should appear

**Desktop**  🤖
 - OS: PopOs!
 - Version: 22.04

**Comment by annawoodard** [comment]
@kraanzu Consider adding instructions to use `?` on the landing page.  I went GitHub readme -> see there are no instructions -> look at the mp4 and pause it at the help menu -> see I should try `ctrl+p` but it doesn't work -> look at the issues and find this one before I saw to try `?`. Thanks for this tool, I'm just trying it out now; it is awesome so far! This will probably be an "everyday" tool for me 😄

**Comment by kraanzu** [comment]
Sorry for the Inconvenience. Yeah I am working on a welcome page that will show the keybinding for help menu!
Lets keep this issue open until that... it shouldn't take long to implement :)

**Comment by annawoodard** [comment]
🙏🙏🙏

**Comment by kraanzu** [comment]
Well.. How's this: ![](https://i.imgur.com/FqSn1wE.png)
