### ISSUE TITLE
[BUG] None returned while trying to read config.yaml

### ISSUE THREAD

**Issue by fallowmcolstein** [kraanzu/dooit#21]
some kind of error, it won't start when I run dooit (in powershell & cmd).
error message:
https://pastebin.com/XCAfMkXm

 - OS: Windows
 - Version 11

**Comment by kraanzu** [comment]
Have you, in any way, changed the config file?

**Comment by fallowmcolstein** [comment]
no. I just ran the install command and installed pyyaml.

**Comment by kraanzu** [comment]
Del the config folder (`~/.config/dooit`) and try to run the app again

**Comment by kraanzu** [comment]
> I don't see a config folder. Where should it be?

As I mentioned, In your home directory..
Just run this:

```python
import os
print(os.path.expanduser('~/.config/dooit/config.yaml')
```

**Comment by rvan-tgm** [comment]
> I don't see a config folder. Where should it be?
In your pastebin row 62 it tells you where your config is located ;)
C:\\Users\YourUsernameHere\.config\dooit

**Comment by fallowmcolstein** [comment]
ok I deleted it but it still doesn't work.

**Comment by kraanzu** [comment]
@fallowmcolstein you have updated right?

**Comment by fallowmcolstein** [comment]
ehh what do you mean?

**Comment by fallowmcolstein** [comment]
I deleted the file, if that's what you mean

**Comment by fallowmcolstein** [comment]
Oh  yeah I tried that. Doesn't work. When I install it it does give this error, that might have something to do with it...

**Comment by kraanzu** [comment]
Oh i need to bump the version in that repo, But it should still install the updated version right?
Maybe try uninstalling gupshup if it doesn't

**Comment by fallowmcolstein** [comment]
How do I uninstall that?

**Comment by kraanzu** [comment]
```bash
pip uninstall gupshup
pip uninstall dooit
git clone https://github.com/kraanzu/dooit.git
cd dooit
pip3 install .
```

**Comment by fallowmcolstein** [comment]
When I ran pip uninstall gupshup it said it wasn't even installed, so I tried installing it and reinstalling dooit and now it's giving a different error...
https://pastebin.com/vzKvDBYJ

**Comment by kraanzu** [comment]
Yes I am looking into it right now.. Will update you soon (it has something to do with windows).
Sorry for the inconvenience :(
