### ISSUE TITLE
💡 [FEAT]New features list, list of known bugs, priority list?

### ISSUE THREAD

**Issue by roundmammouth** [kraanzu/dooit#23]
**Is your feature request related to a problem? 😢 Please describe.** 
I'm going to start using this code this weekend and wanted to know where a python newbie should start... so I usually start with a todo list. This would automate a chunk of things, where would I find one to read, update or should we create first, but didnt see one other than issues.

**Describe the solution you'd like**   🤔
Well its a duplex solution, first an apriori sorted dooit list that we can use to update the code, a similar feature for us to enter and sort our data for us. I've been expanding a self sorting list for a while and this code might be a good fit.

**Describe alternatives you've considered**  🧐
Django TODO is pretty good but i'm not the best with django.

**Additional context** 📝
Willing to help write code, tests, documentation and features while I get up to speed then add functions. =)

**Comment by kraanzu** [comment]
Like... you want a automation script that does the work for you?
For e.g. : Let's sat you want to save upcoming hackathons and want to save them automatically to the todo list using a script?

**Comment by kraanzu** [comment]
Closing as stale
