### ISSUE TITLE
[BUG] Emojis are not displayed correctly

### ISSUE THREAD

**Issue by TakshPanchal** [kraanzu/dooit#24]
**Describe the bug** 🐛
Hey, I love your project and the idea. It will be so much useful for me personally. Thank you to the team.
I found some issues in my terminal can you help me to solve?

**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/52617262/174646271-3b4c28e1-120e-4eff-b059-ab31a26ec281.png)

**Desktop (please complete the following information):**  🤖
- OS: Ubuntu
= Version 22.04 LTS

**Additional context** 📝
Also, Can you make any contribution guidelines! I really wanted to contribute to this project and help to solve bugs and add features.

**Comment by kraanzu** [comment]
Use a [nerd font](https://www.nerdfonts.com/) or change the icons in the config

**Comment by kraanzu** [comment]
> Also, Can you make any contribution guidelines! I really wanted to contribute to this project and help to solve bugs and add features.

Sorry I was on mobile phone last night and didn't see your message properly :(
Sure thing, PRs are always welcome. Anything from a small refactor to a feature, If you want to help in any way feel free to open a PR.
Ping me if you need any help :)
