### ISSUE TITLE
💡 [FEAT] Ability to create templates in yml or toml

### ISSUE THREAD

**Issue by cocoonkid** [kraanzu/dooit#27]
I'd like to be able to open todo templates easily in the terminal and work through them.
Even better would be to be able to save state to a "<name>-dooit-<datetime> file or be able to configure the filename.

I would use this for web application pen-tests and to quickly share my status or keep the file under version control.

**Comment by kraanzu** [comment]
Yes I am currently working on this and will push an update soon :)

**Comment by cocoonkid** [comment]
Very cool. I want to contribute to this project. But I am a noob. Let's dooit :)

Will test as soon as it's released :)

**Comment by kraanzu** [comment]
Hey @cocoonkid, I've changed the data storage location from `~/.config` to 
`$XDG_DATA_HOME` (or `~/.local/share/dooit/todo.yaml`) 
I've tried to maintain the format according to [todo.txt](https://github.com/todotxt/todo.txt)
Maybe see for yourself and lemme know your thoughts on it?

**Comment by kraanzu** [comment]
I'll be closing this for now :)

**Comment by cocoonkid** [comment]
@kraanzu  well done!  Now I can also try to sync it :-) Will report back!
