### ISSUE TITLE
💡 [FEAT] remove Menu + icon and Todos+Icon.

### ISSUE THREAD

**Issue by cocoonkid** [kraanzu/dooit#29]
💡 [FEAT] remove Menu + icon and Todos+Icon.

In my humble opinion it is clear as ice what the left and right side are supposed to be.

So that would free screen estate for the list and topics itself.

**Comment by kraanzu** [comment]
Yes ig you may be right... That was just for aesthetics.
I will push an update in which you can set to show them or not in the config file
