### ISSUE TITLE
[BUG] Tasks do not persist between dooit sessions

### ISSUE THREAD

**Issue by annawoodard** [kraanzu/dooit#31]
**Describe the bug** 🐛
After closing and re-opening the shell dooit is running in, all of my tasks have disappeared.

**To Reproduce** 🐣
1. Run `dooit`
2. Put in some tasks
3. Close the shell dooit is running in
4. Run `dooit`; old tasks are gone

**Expected behavior**  🤔 
I expect tasks to persist between dooit sessions.

**Desktop (please complete the following information):**  🤖
 - OS: MacOS 
 - Version: Monterey 12.3.1

**Comment by kraanzu** [comment]
Did  you quit  dooit with either `ctrl+c` or `ctrl+q` ?
dooit does not saves task on edit, it only does when quit keybindings are triggered

**Comment by kraanzu** [comment]
> a customizable autosave routine would be highly appreciated ?!

I suppose saving the todo on each edit should be fine but haven't tested that for having a much larger data.
I'll stress test and see if that does not cause too much delay, we can move the saving part to a thread for non-disruptive flow :)

**Comment by cocoonkid** [comment]
@kraanzu  I don't think this will interfere with the syncthing sync that I will enable for the data file but I will report back how that works.

**Comment by LevitatingBusinessMan** [comment]
I am even experiencing this issue while closing `dooit` normally...
