### ISSUE TITLE
[BUG] Exception on launch

### ISSUE THREAD

**Issue by CharlieC57** [kraanzu/dooit#32]
**Describe the bug** 🐛
Failure on launch. Throws multiple exceptions, then exits

**To Reproduce** 🐣
1. Launch dooit through the terminal

**Expected behavior**  🤔 
Run the app 

**Screenshots** 🧐
![imagen](https://user-images.githubusercontent.com/23264837/174897526-99e70f0e-8115-4047-9e57-7f4be5dfbff7.png)
![imagen](https://user-images.githubusercontent.com/23264837/174897615-5458745a-4c95-486a-949b-f0603dc112f9.png)

**Desktop (please complete the following information):**  🤖
 - OS: Fedora
 - Version 36
 - Python Version: 3.10.5

**Additional context** 📝
Worked fine upon installation, came back the next day to this issue. I can´t trace if this is due to system updates, but it seems something regarding **textual** blew into smitherines

**Comment by kraanzu** [comment]
@orsenthil Sorry for the inconvenience. That is my fault for not checking  for `$XDG_CONFIG_HOME` while making the config. I'll push an update soon :)

**Comment by kraanzu** [comment]
As for @CharlieC57, I suppose your screenshot does not contain the whole error message. Maybe share that using [pastebin](https://pastebin.com/index.php)?
Though it might be the same reason as @orsenthil's but just in case :)

**Comment by kraanzu** [comment]
I'll push an update soon. Hopefully it solves that

**Comment by kraanzu** [comment]
Hey there @orsenthil and @CharlieC57 can you please update and check if it's working properly now?

**Comment by CharlieC57** [comment]
No luck, although looking up the error it may be related to the .pkl file being empty. Is it supposed to be empty at installation?

**Comment by kraanzu** [comment]
Not empty...just the default implementation of data types... I suggest that you delete the whole dooit folder in config and then re run and see if that works.
Apologies for so much hassle :(

**Comment by CharlieC57** [comment]
No worries, did what you suggested and is looking fine :)
You may close this issue at least from my end, hopefully it works for @orsenthil as well.

**Comment by kraanzu** [comment]
>  hopefully it works for @orsenthil as well.

I think that it should, The issue was that Path was not expanding `~` which caused an error :)
