### ISSUE TITLE
[BUG]UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position 1: encoding error

### ISSUE THREAD

**Issue by myt2000** [kraanzu/dooit#35]
run in window 10

1.git clone https://github.com/kraanzu/dooit.git
2. cd dooit
3. pip3 install .
4. dooit

1. Entering `dooit` for the first time shows a black screen

2. Entering `dooit` for the first time error log
───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\python3.10\lib\site-packages\textual\widget.py:202 in _get_lines         │
│                                                                             │
│   199 │   def _get_lines(self) -> Lines:                                    │
│   200 │   │   """Get segment lines to render the widget."""                 │
│   201 │   │   if self.render_cache is None:                                 │
│ > 202 │   │   │   self.render_lines()                                       │
│   203 │   │   assert self.render_cache is not None                          │
│   204 │   │   lines = self.render_cache.lines                               │
│   205 │   │   return lines                                                  │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:188 in render_lines       │
│                                                                             │
│   185 │                                                                     │
│   186 │   def render_lines(self) -> None:                                   │
│   187 │   │   width, height = self.size                                     │
│ > 188 │   │   renderable = self.render_styled()                             │
│   189 │   │   options = self.console.options.update_dimensions(width, heigh │
│   190 │   │   lines = self.console.render_lines(renderable, options)        │
│   191 │   │   self.render_cache = RenderCache(self.size, lines)             │
│                                                                             │
│ ┌──────────────── locals ────────────────┐                                  │
│ │ height = 1                             │                                  │
│ │   self = StatusBar(name='StatusBar#1') │                                  │
│ │  width = 77                            │                                  │
│ └────────────────────────────────────────┘                                  │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:128 in render_styled      │
│                                                                             │
│   125 │   │   Returns:                                                      │
│   126 │   │   │   RenderableType: A new renderable.                         │
│   127 │   │   """                                                           │
│ > 128 │   │   renderable = self.render()                                    │
│   129 │   │   if self.padding is not None:                                  │
│   130 │   │   │   renderable = Padding(renderable, self.padding)            │
│   131 │   │   if self.border in self.BOX_MAP:                               │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:81 in render │
│                                                                             │
│    78 │   │   │   status,                                                   │
│    79 │   │   │   message,                                                  │
│    80 │   │   │   Text(                                                     │
│ >  81 │   │   │   │   self.get_date(),                                      │
│    82 │   │   │   │   style=style_date,                                     │
│    83 │   │   │   ),                                                        │
│    84 │   │   │   Text(                                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         bar = <rich.table.Table object at 0x0000019A74611360>           │ │
│ │     message = <text '                                                   │ │
│ │               ' []>                                                     │ │
│ │        self = StatusBar(name='StatusBar#1')                             │ │
│ │      status = <text ' NORMAL' []>                                       │ │
│ │ style_clock = 'reverse yellow'                                          │ │
│ │  style_date = 'reverse green'                                           │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:45 in        │
│ get_date                                                                    │
│                                                                             │
│    42 │   │   """                                                           │
│    43 │   │   Returns current time                                          │
│    44 │   │   """                                                           │
│ >  45 │   │   return f"{datetime.today().strftime(f' {self.calendar_icon}   │
│    46 │                                                                     │
│    47 │   def set_status(self, status: StatusType) -> None:                 │
│    48 │   │   self.status = status                                          │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
└─────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position
1: encoding error
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\python3.10\lib\site-packages\textual\widget.py:202 in _get_lines         │
│                                                                             │
│   199 │   def _get_lines(self) -> Lines:                                    │
│   200 │   │   """Get segment lines to render the widget."""                 │
│   201 │   │   if self.render_cache is None:                                 │
│ > 202 │   │   │   self.render_lines()                                       │
│   203 │   │   assert self.render_cache is not None                          │
│   204 │   │   lines = self.render_cache.lines                               │
│   205 │   │   return lines                                                  │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:188 in render_lines       │
│                                                                             │
│   185 │                                                                     │
│   186 │   def render_lines(self) -> None:                                   │
│   187 │   │   width, height = self.size                                     │
│ > 188 │   │   renderable = self.render_styled()                             │
│   189 │   │   options = self.console.options.update_dimensions(width, heigh │
│   190 │   │   lines = self.console.render_lines(renderable, options)        │
│   191 │   │   self.render_cache = RenderCache(self.size, lines)             │
│                                                                             │
│ ┌──────────────── locals ────────────────┐                                  │
│ │ height = 1                             │                                  │
│ │   self = StatusBar(name='StatusBar#1') │                                  │
│ │  width = 77                            │                                  │
│ └────────────────────────────────────────┘                                  │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:128 in render_styled      │
│                                                                             │
│   125 │   │   Returns:                                                      │
│   126 │   │   │   RenderableType: A new renderable.                         │
│   127 │   │   """                                                           │
│ > 128 │   │   renderable = self.render()                                    │
│   129 │   │   if self.padding is not None:                                  │
│   130 │   │   │   renderable = Padding(renderable, self.padding)            │
│   131 │   │   if self.border in self.BOX_MAP:                               │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:81 in render │
│                                                                             │
│    78 │   │   │   status,                                                   │
│    79 │   │   │   message,                                                  │
│    80 │   │   │   Text(                                                     │
│ >  81 │   │   │   │   self.get_date(),                                      │
│    82 │   │   │   │   style=style_date,                                     │
│    83 │   │   │   ),                                                        │
│    84 │   │   │   Text(                                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         bar = <rich.table.Table object at 0x0000019A74611840>           │ │
│ │     message = <text '                                                   │ │
│ │               ' []>                                                     │ │
│ │        self = StatusBar(name='StatusBar#1')                             │ │
│ │      status = <text ' NORMAL' []>                                       │ │
│ │ style_clock = 'reverse yellow'                                          │ │
│ │  style_date = 'reverse green'                                           │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:45 in        │
│ get_date                                                                    │
│                                                                             │
│    42 │   │   """                                                           │
│    43 │   │   Returns current time                                          │
│    44 │   │   """                                                           │
│ >  45 │   │   return f"{datetime.today().strftime(f' {self.calendar_icon}   │
│    46 │                                                                     │
│    47 │   def set_status(self, status: StatusType) -> None:                 │
│    48 │   │   self.status = status                                          │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
└─────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position
1: encoding error
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\python3.10\lib\site-packages\textual\widget.py:202 in _get_lines         │
│                                                                             │
│   199 │   def _get_lines(self) -> Lines:                                    │
│   200 │   │   """Get segment lines to render the widget."""                 │
│   201 │   │   if self.render_cache is None:                                 │
│ > 202 │   │   │   self.render_lines()                                       │
│   203 │   │   assert self.render_cache is not None                          │
│   204 │   │   lines = self.render_cache.lines                               │
│   205 │   │   return lines                                                  │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:188 in render_lines       │
│                                                                             │
│   185 │                                                                     │
│   186 │   def render_lines(self) -> None:                                   │
│   187 │   │   width, height = self.size                                     │
│ > 188 │   │   renderable = self.render_styled()                             │
│   189 │   │   options = self.console.options.update_dimensions(width, heigh │
│   190 │   │   lines = self.console.render_lines(renderable, options)        │
│   191 │   │   self.render_cache = RenderCache(self.size, lines)             │
│                                                                             │
│ ┌──────────────── locals ────────────────┐                                  │
│ │ height = 1                             │                                  │
│ │   self = StatusBar(name='StatusBar#1') │                                  │
│ │  width = 77                            │                                  │
│ └────────────────────────────────────────┘                                  │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:128 in render_styled      │
│                                                                             │
│   125 │   │   Returns:                                                      │
│   126 │   │   │   RenderableType: A new renderable.                         │
│   127 │   │   """                                                           │
│ > 128 │   │   renderable = self.render()                                    │
│   129 │   │   if self.padding is not None:                                  │
│   130 │   │   │   renderable = Padding(renderable, self.padding)            │
│   131 │   │   if self.border in self.BOX_MAP:                               │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:81 in render │
│                                                                             │
│    78 │   │   │   status,                                                   │
│    79 │   │   │   message,                                                  │
│    80 │   │   │   Text(                                                     │
│ >  81 │   │   │   │   self.get_date(),                                      │
│    82 │   │   │   │   style=style_date,                                     │
│    83 │   │   │   ),                                                        │
│    84 │   │   │   Text(                                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         bar = <rich.table.Table object at 0x0000019A74610CA0>           │ │
│ │     message = <text '                                                   │ │
│ │               ' []>                                                     │ │
│ │        self = StatusBar(name='StatusBar#1')                             │ │
│ │      status = <text ' NORMAL' []>                                       │ │
│ │ style_clock = 'reverse yellow'                                          │ │
│ │  style_date = 'reverse green'                                           │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:45 in        │
│ get_date                                                                    │
│                                                                             │
│    42 │   │   """                                                           │
│    43 │   │   Returns current time                                          │
│    44 │   │   """                                                           │
│ >  45 │   │   return f"{datetime.today().strftime(f' {self.calendar_icon}   │
│    46 │                                                                     │
│    47 │   def set_status(self, status: StatusType) -> None:                 │
│    48 │   │   self.status = status                                          │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
└─────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position
1: encoding error
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\python3.10\lib\site-packages\textual\widget.py:202 in _get_lines         │
│                                                                             │
│   199 │   def _get_lines(self) -> Lines:                                    │
│   200 │   │   """Get segment lines to render the widget."""                 │
│   201 │   │   if self.render_cache is None:                                 │
│ > 202 │   │   │   self.render_lines()                                       │
│   203 │   │   assert self.render_cache is not None                          │
│   204 │   │   lines = self.render_cache.lines                               │
│   205 │   │   return lines                                                  │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:188 in render_lines       │
│                                                                             │
│   185 │                                                                     │
│   186 │   def render_lines(self) -> None:                                   │
│   187 │   │   width, height = self.size                                     │
│ > 188 │   │   renderable = self.render_styled()                             │
│   189 │   │   options = self.console.options.update_dimensions(width, heigh │
│   190 │   │   lines = self.console.render_lines(renderable, options)        │
│   191 │   │   self.render_cache = RenderCache(self.size, lines)             │
│                                                                             │
│ ┌──────────────── locals ────────────────┐                                  │
│ │ height = 1                             │                                  │
│ │   self = StatusBar(name='StatusBar#1') │                                  │
│ │  width = 77                            │                                  │
│ └────────────────────────────────────────┘                                  │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:128 in render_styled      │
│                                                                             │
│   125 │   │   Returns:                                                      │
│   126 │   │   │   RenderableType: A new renderable.                         │
│   127 │   │   """                                                           │
│ > 128 │   │   renderable = self.render()                                    │
│   129 │   │   if self.padding is not None:                                  │
│   130 │   │   │   renderable = Padding(renderable, self.padding)            │
│   131 │   │   if self.border in self.BOX_MAP:                               │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:81 in render │
│                                                                             │
│    78 │   │   │   status,                                                   │
│    79 │   │   │   message,                                                  │
│    80 │   │   │   Text(                                                     │
│ >  81 │   │   │   │   self.get_date(),                                      │
│    82 │   │   │   │   style=style_date,                                     │
│    83 │   │   │   ),                                                        │
│    84 │   │   │   Text(                                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         bar = <rich.table.Table object at 0x0000019A74611BA0>           │ │
│ │     message = <text '                                                   │ │
│ │               ' []>                                                     │ │
│ │        self = StatusBar(name='StatusBar#1')                             │ │
│ │      status = <text ' NORMAL' []>                                       │ │
│ │ style_clock = 'reverse yellow'                                          │ │
│ │  style_date = 'reverse green'                                           │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:45 in        │
│ get_date                                                                    │
│                                                                             │
│    42 │   │   """                                                           │
│    43 │   │   Returns current time                                          │
│    44 │   │   """                                                           │
│ >  45 │   │   return f"{datetime.today().strftime(f' {self.calendar_icon}   │
│    46 │                                                                     │
│    47 │   def set_status(self, status: StatusType) -> None:                 │
│    48 │   │   self.status = status                                          │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
└─────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position
1: encoding error
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ F:\python3.10\lib\site-packages\textual\widget.py:202 in _get_lines         │
│                                                                             │
│   199 │   def _get_lines(self) -> Lines:                                    │
│   200 │   │   """Get segment lines to render the widget."""                 │
│   201 │   │   if self.render_cache is None:                                 │
│ > 202 │   │   │   self.render_lines()                                       │
│   203 │   │   assert self.render_cache is not None                          │
│   204 │   │   lines = self.render_cache.lines                               │
│   205 │   │   return lines                                                  │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:188 in render_lines       │
│                                                                             │
│   185 │                                                                     │
│   186 │   def render_lines(self) -> None:                                   │
│   187 │   │   width, height = self.size                                     │
│ > 188 │   │   renderable = self.render_styled()                             │
│   189 │   │   options = self.console.options.update_dimensions(width, heigh │
│   190 │   │   lines = self.console.render_lines(renderable, options)        │
│   191 │   │   self.render_cache = RenderCache(self.size, lines)             │
│                                                                             │
│ ┌──────────────── locals ────────────────┐                                  │
│ │ height = 1                             │                                  │
│ │   self = StatusBar(name='StatusBar#1') │                                  │
│ │  width = 77                            │                                  │
│ └────────────────────────────────────────┘                                  │
│                                                                             │
│ F:\python3.10\lib\site-packages\textual\widget.py:128 in render_styled      │
│                                                                             │
│   125 │   │   Returns:                                                      │
│   126 │   │   │   RenderableType: A new renderable.                         │
│   127 │   │   """                                                           │
│ > 128 │   │   renderable = self.render()                                    │
│   129 │   │   if self.padding is not None:                                  │
│   130 │   │   │   renderable = Padding(renderable, self.padding)            │
│   131 │   │   if self.border in self.BOX_MAP:                               │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:81 in render │
│                                                                             │
│    78 │   │   │   status,                                                   │
│    79 │   │   │   message,                                                  │
│    80 │   │   │   Text(                                                     │
│ >  81 │   │   │   │   self.get_date(),                                      │
│    82 │   │   │   │   style=style_date,                                     │
│    83 │   │   │   ),                                                        │
│    84 │   │   │   Text(                                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         bar = <rich.table.Table object at 0x0000019A74668550>           │ │
│ │     message = <text '                                                   │ │
│ │               ' []>                                                     │ │
│ │        self = StatusBar(name='StatusBar#1')                             │ │
│ │      status = <text ' NORMAL' []>                                       │ │
│ │ style_clock = 'reverse yellow'                                          │ │
│ │  style_date = 'reverse green'                                           │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ F:\python3.10\lib\site-packages\dooit\ui\widgets\status_bar.py:45 in        │
│ get_date                                                                    │
│                                                                             │
│    42 │   │   """                                                           │
│    43 │   │   Returns current time                                          │
│    44 │   │   """                                                           │
│ >  45 │   │   return f"{datetime.today().strftime(f' {self.calendar_icon}   │
│    46 │                                                                     │
│    47 │   def set_status(self, status: StatusType) -> None:                 │
│    48 │   │   self.status = status                                          │
│                                                                             │
│ ┌─────────────── locals ───────────────┐                                    │
│ │ self = StatusBar(name='StatusBar#1') │                                    │
│ └──────────────────────────────────────┘                                    │
└─────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'locale' codec can't encode character '\uf5f4' in position
1: encoding error

**Comment by kraanzu** [comment]
> │ > 45 │ │ return f"{datetime.today().strftime(f' {self.calendar_icon}'")  

Looks like a font issue. Are you using windows terminal?

**Comment by myt2000** [comment]
> 

yes , run in windows 10 system
