### ISSUE TITLE
Config file empty

### ISSUE THREAD

**Issue by DevFlock** [kraanzu/dooit#4]
Using python3.10, windows

.config/dooit/config.yaml file is empty. Tried to use the example_config.yaml but it errors saying `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 145: character maps to <undefined>`

**Comment by kraanzu** [comment]
Yeah had the same issue on my other project as well... Windows doesn't seem to handle this fonts well. Maybe try after installing a  [nerd font](https://www.nerdfonts.com/) ?

**Comment by DevFlock** [comment]
I have fira code in vscode and also use ibm plex mono which are both listed on the nerd code website. Both show up as errors

**Comment by kraanzu** [comment]
@DevFlock  I've pushed an update...could you please check if it's working now?

**Comment by DevFlock** [comment]
Yeah this seems to fix the loading issue. Just the icons don't seem to show but that is a font issue

**Comment by kraanzu** [comment]
Glad to hear that, You can always change the icons from the config menu to suit your font.
Anyways, I'll close this for now then :)
