### ISSUE TITLE
💡 [FEAT] Add different colour for prorities

### ISSUE THREAD

**Issue by CptIceberg** [kraanzu/dooit#40]
**Is your feature request related to a problem? 😢 Please describe.** 
I find the priorities of the tasks to be hardly readable.

**Describe the solution you'd like**   🤔
A different colour for the line, or at least the priority number would be great to see them better.
This could be a setting in the config.yaml file too, so those could be modified (from a list of available colours/colours codes ? 

**Describe alternatives you've considered**  🧐
The sorting feature is already great for that !

**Additional context** 📝
I'm coming from using a todo.txt format in a markdown editor (in Joplin), and found the different colouring to be really important to visualize fastly what is important in subtasks. I was looking for a todo editor in the terminal, and found yours the most user friendly.
I would try this feature addition myself  (and probably will), but my Python skills aren't good at all :sweat_smile:

**Comment by kraanzu** [comment]
something like this?
![](https://i.imgur.com/MM0Hjjc.png)

**Comment by CptIceberg** [comment]
This looks great !

**Comment by kraanzu** [comment]
I see, then I'll throw in an option in the config to either use numbers or colors to represent the urgency :)

**Comment by CptIceberg** [comment]
Thank you very much, that was fast as hell !

**Comment by kraanzu** [comment]
> Thank you very much, that was fast as hell !

Well I am excited too. I never thought that dooit will be used by so many people.
Thank you so much :)
I'll push the update after a couple of hours.

**Comment by CptIceberg** [comment]
This is great thank you very much :pray:
