### ISSUE TITLE
[Suggestion]  change move_focus_to_menu: h   -> move_focus_to_topics

### ISSUE THREAD

**Issue by cocoonkid** [kraanzu/dooit#42]
[Suggestion]  change move_focus_to_menu: h   -> move_focus_to_topics

I'd also add 

move_focus_to_tasks: l

That would be great! The current default is Return which is suboptimal for my case.

**Comment by kraanzu** [comment]
Well you can change that in the config :)

**Comment by cocoonkid** [comment]
just realized I can change 

select_node: l

:)

the name change still stands hehe

**Comment by kraanzu** [comment]
> the name change still stands hehe

Yes, that needs renaming :)

**Comment by moaojarco** [comment]
I'm using like this:
```
select_node: [l, ctrl+i]
move_focus_to_menu: [h, ctrl+i]
```
ctrl+i = Tab
So i just press **Tab** to move between windows

**Comment by cocoonkid** [comment]
@moaojarco  great solution. Thanks for this!
