### ISSUE TITLE
[BUG] Show warning if user starts another instance

### ISSUE THREAD

**Issue by shetozz** [kraanzu/dooit#45]
Tasks don't get saved if 2 windows are opened.

**To Reproduce** 🐣
1. Open 2 separate windows of Dooit and leave one of them on the welcome screen (sometimes it works even if you are not on the welcome screen).
1. Add a task to the other one.
1. Close the window that you add the task to first.

**Expected behavior**  🤔 
the task now is not in the other window, when you close it and reopen it the task won't be there either.

**Screenshots** 🧐
![Dooit_bug_1](https://user-images.githubusercontent.com/93838524/175864212-6f29b235-4b7f-4ca1-a207-1fef14fb9ec9.png)
![Dooit_bug_2](https://user-images.githubusercontent.com/93838524/175864223-247461e4-92f4-4969-a16d-b0874aa462ee.png)

**Desktop (please complete the following information):**  🤖
 - OS: Fedora linux
 - Version 36
**Additional context** 📝
Kitty terminal emulator

**Comment by kraanzu** [comment]
I'm sorry but this will result in complications...
I saw that task-warrior has this functionality but dooit has nested todos/topics which will cause strange behaviour.
Also, Running two instances at a time seems like a very very rare situation.Therefore, I'll not be implementing this feature.

**Comment by shetozz** [comment]
Running two instances is a rare thing but it's often by mistake, I had one opened on another workspace and I forgot about it, so if it's easy to have an indicator that tells you "there's an instance already opened" or something, that will fix the issue

**Comment by kraanzu** [comment]
> it's easy to have an indicator that tells you "there's an instance already opened" or something

Well that is something i can do i guess... I'll look into it :)
