### ISSUE TITLE
[BUG] "One instance of dooit is already running!" error

### ISSUE THREAD

**Issue by gilbh** [kraanzu/dooit#49]
Hi,
This happens when I am try to run `dooit.exe` from the command line. Here's what I am getting:
```
C:\Users\gilbe\Envs\utils\Scripts>dooit.exe
One instance of dooit is already running!
Quiting...
```

1. Open `cmd`
2. Type `dooit`
3. See error

 - OS: Windows
 - Version: 11

I ran the `pip install` from inside my envs (which is called `Utils`

Thanks!!

**Comment by TyBalduf** [comment]
Seems like this commit introduced the error https://github.com/kraanzu/dooit/commit/e1d08b1b95183583cd5b05b7d8afb8391a65db15

**Comment by kraanzu** [comment]
hey @gilbh, can you update and re-check if it's working now?

**Comment by TyBalduf** [comment]
@kraanzu I still have the same issue after updating. I did some debugging and it looks like `PID = getpid()` is getting the PID for python.exe rather than dooit.exe. 

I think a simple fix would just be to check if you come across multiple dooit/dooit.exe processes. As long as there is only one (i.e. the one currently executing), it can run. Any more than one means there is already a dooit instance executing somewhere else on that machine.

**Comment by gilbh** [comment]
Thanks. 

Is there a new build to re-install and check? (I am novice in github etc ...) ... I tried running the source but I get:
```
(utils) C:\Users\gilbe\Envs\utils\Lib\site-packages\dooit>python __init__.py
Traceback (most recent call last):
  File "C:\Users\gilbe\Envs\utils\Lib\site-packages\dooit\__init__.py", line 2, in <module>
    from .ui.tui import Doit
ImportError: attempted relative import with no known parent package
```

**Comment by kraanzu** [comment]
> Is there a new build to re-install and check?

Yes!

> python __init__.py

No you are not supposed to do that...It won't work that way
Just run this:

```bash
python3 -m pip install git+https://github.com/kraanzu/dooit.git
```

**Comment by gilbh** [comment]
Thank you!

I ran
```
python3 -m pip install git+https://github.com/kraanzu/dooit.git
```
-- and still got the same error. I then tried:
```
python3 -m pip install --force-reinstall git+https://github.com/kraanzu/dooit.git
```
-- and still got the error.

Please advise, with thanks.

**Comment by kraanzu** [comment]
This is strange... It  means that you have yet another `dooit.exe` running. Guess I'll add a time difference check too :)

**Comment by TyBalduf** [comment]
@kraanzu I think he is having the same issue I describe. It's not that there are multiple dooit instances, it's that the PID you are comparing against is for python.exe not dooit.exe.

**Comment by kraanzu** [comment]
Hey @TyBalduf,
>  it's that the PID you are comparing against is for python.exe

Hmm, that seems strange. Since we are comparing both name and the pid, It shouldn't be the case ig.

Idk how windows does this but when I made a seperate test file to run dooit i get this:
> psutil.Process(pid=79038, name='python', status='sleeping', started='08:53:27')

So the function should have returned `False`

**Comment by kraanzu** [comment]
Hey @gilbh ,
Can you check what's the output of this code:

```python
from os import getpid
import psutil

PID = getpid()
for process in psutil.process_iter():
    if process.name() in ["dooit", "dooit.exe"] and process.pid != PID:
        print(process)
```

**Comment by TyBalduf** [comment]
@kraanzu 

```
def is_running():
    PID = getpid()
    print(f"Initial PID: {PID}")
    for process in psutil.process_iter():
        print(process)
        if process.name() in ["dooit", "dooit.exe"] and process.pid != PID:
            return True
    return False
```
If I add these print statements to `is_running`, here is a (truncated) version of my output.
```
Initial PID: 33308
psutil.Process(pid=0, name='System Idle Process', status='running')
psutil.Process(pid=4, name='System', status='running')
psutil.Process(pid=104, name='', status='stopped', started='2022-06-20 23:22:10')
...
psutil.Process(pid=33308, name='python.exe', status='running', started='09:29:22')
...
psutil.Process(pid=39060, name='chrome.exe', status='running', started='09:19:51')
psutil.Process(pid=39472, name='dooit.exe', status='running', started='09:29:22')
One instance of dooit is already running!
Quiting...
```

So the if statement gets entered because it found `process.name()==dooit.exe`, but the initial PID its comparing against isn't for another instance of `dooit.exe`, but for `python.exe`, so naturally `process.pid != PID`. 

I'm not sure how to ensure that `getpid` would give you the pid for `dooit.exe`, so I think just counting the number of dooit instances might work easier on all platforms.

**Comment by kraanzu** [comment]
Hey @gilbh , It should work as expected now :)

**Comment by kraanzu** [comment]
Sync implemented in v.1.0
