### ISSUE TITLE
Error on python version

### ISSUE THREAD

**Issue by Basile-LAMOTTE** [kraanzu/dooit#5]
Running `python3 -m pip install git+https://github.com/kraanzu/dooit.git`
throw: `ERROR: Package 'dooit-0.1.0' requires a different Python: 3.8.10 not in '>=3.10,<4.0'`.
I tried again with other versions of python, but nothing worked. Am I missing something ?

**Comment by DevFlock** [comment]
You need to use python 3.10 or later

**Comment by Basile-LAMOTTE** [comment]
thank you

**Comment by alichtman** [comment]
Due to use of the `match` feature, which is introduced in Python 3.10, this is a real requirement.

https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching

**Comment by kraanzu** [comment]
Looks like this has been resolved so I'll be closing this :)
