### ISSUE TITLE
💡 [FEAT] Configure storage location of `todo.yaml`

### ISSUE THREAD

**Issue by phylor** [kraanzu/dooit#51]
**Is your feature request related to a problem? 😢 Please describe.** 
I really like the simplicity of dooit and the vim-like keybindings! The problem with todos for me is that I need them synced across devices as I'm not always at the same computer.

**Describe the solution you'd like**   🤔
I imagine that I could set the location of the `todo.yaml` in the config file. That way, I could move the location to a directory which is synced across devices.

This might eventually lead to conflicts, which would be handled by the sync though (so no need for dooit to support that).

**Describe alternatives you've considered**  🧐
I guess I could just move the `todo.yaml` to my sync directory and symlink it to the location where dooit expects it. However, specifying a location in dooit seems cleaner to me. It would also allow to use different storage files. Let's say, if you have one for work and one for personal todos. Although changing the config file everytime you want to switch is probably not the cleanest. Maybe a command line switch to dooit itself would be cleaner in this case.

**Comment by kraanzu** [comment]
Yes, I think it would be great.

**Comment by kraanzu** [comment]
Hey @phylor, I think you can create a symlink that will work better and be a cleaner approach.
