### ISSUE TITLE
[BUG] Esc within tmux makes dooit unresponsive

### ISSUE THREAD

**Issue by phylor** [kraanzu/dooit#52]
**Describe the bug** 🐛
Pressing `Esc` in input mode makes dooit unresponsive within tmux.

**To Reproduce** 🐣
1. Start `tmux`
2. Start `dooit` from within `tmux`
3. Go to insert mode, e.g. by adding a task
4. Press `Esc` to go back to normal mode

dooit is now unresponsive. Key presses don't have any effect anymore.

When running dooit without tmux, that behavior is not present. Exiting input mode works perfectly.

**Desktop (please complete the following information):**  🤖
 - OS: ArchLinux, installed via pip
 - Version: 0.2.0

**Comment by kraanzu** [comment]
Hmm, that seems strange. 
Running tmux with my custom configs does not seem to have any problem but It does have a slight lag with vanilla config. I'll do some digging and let you know :)

**Comment by kraanzu** [comment]
Hey @phylor, You need to add this in your tmux config:
```
set -s escape-time 0
```
Reference: [stack exchange](https://superuser.com/questions/252214/slight-delay-when-switching-modes-in-vim-using-tmux-or-screen/252717#252717)

**Comment by phylor** [comment]
@kraanzu That works, thank you!

Should this be documented somewhere in dooit, as it has problems with the tmux default config?

vim has a similar issue, but doesn't get unresponsive - it just takes a bit of time to get from input mode to command mode.

**Comment by kraanzu** [comment]
Yeah good idea. I'll update the README
