### ISSUE TITLE
[BUG] Broken child topic behaviour

### ISSUE THREAD

**Issue by shetozz** [kraanzu/dooit#54]
If you make changes to the todo list or the topic list and then close the app short after, it doesn't work as expected, I'll give an example that is broken every time in the how-to reproduce section but it's not the only one.

**To Reproduce** 🐣
1. Create a main Topic and add todos to it
2. Create a child Topic and add todos to it
3. Close the app short after creating these

**Expected behavior**  🤔 
the child topic will be broken (duplicated and missing some of its content)

**Screenshots** 🧐
![image](https://user-images.githubusercontent.com/93838524/176549957-b944c2bc-2545-4aa7-abd3-c6b76d391368.png)

![image](https://user-images.githubusercontent.com/93838524/176550138-15e055d1-1874-4d66-9eeb-984a60bb469b.png)

![image](https://user-images.githubusercontent.com/93838524/176550369-8dbf0acb-754a-4c5b-b56e-70266be9f2ce.png)

**Desktop (please complete the following information):**  🤖
 - OS: Linux (Fedora 36)

**Comment by kraanzu** [comment]
Seems like there's an issue while parsing. I'll push an update soon :)

**Comment by shetozz** [comment]
sorry for this noob question but I installed via pip and doing a pip upgrade for the package doesn't get me the update, is there something I'm doing wrong here?

**Comment by kraanzu** [comment]
> is there something I'm doing wrong here?

Yes, The updated version is only on github.. I haven't yet pushed it to pypi.
You can do this for now:

```
python3 -m pip install git+https://github.com/kraanzu/dooit.git
```
