### ISSUE TITLE
[BUG] Option-backspace (word delete) freezes dooit

### ISSUE THREAD

**Issue by jacksongoode** [kraanzu/dooit#57]
**Describe the bug** 🐛
Append task to topic and type name, then use option+delete to backspace word - dooit freezes.

**To Reproduce** 🐣
1. Append task to topic and type name
2. Option+delete to backspace word
3. dooit freezes.

**Expected behavior**  🤔 
Deletes previous

**Desktop (please complete the following information):**  🤖
 - OS: macOS
 - Version Latest

**Comment by kraanzu** [comment]
Hey @jacksongoode,
I suppose `option` is same as `alt` key on linux/win?
If yes, then it's textual (the TUI framework)'s issue 

Also, there are some key bindings issues the terminal (for e.g. `ctrl+backspace` gets mapped as `backspace` only) 
See [this](https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode/563480#563480) for more details
Currently you can use `ctrl+w` / `control+w` for deleting a word while in insert mode

**Comment by jacksongoode** [comment]
It looks like it was resolved [here](https://github.com/Textualize/textual/pull/539). Maybe you need to update the dependency?

**Comment by kraanzu** [comment]
Alt still manages to mess things up after the latest update, at least on my machine,  it freezes the other key inputs until I press escape. I'm sorry about that :(
I'm closing this issue as of now, I'll be sure to mention if this problem goes away
