### ISSUE TITLE
[BUG] config parser

### ISSUE THREAD

**Issue by Itsnexn** [kraanzu/dooit#64]
**Describe the bug** 🐛
the problem is when you get any exceptions on the parser you make new config which means you overwrite the existing config which means this will remove the old configurations

**To Reproduce** 🐣
1. just comment something I initially commented the banner and when I started the app it overwrote my config with the [example_config.yml](https://github.com/kraanzu/dooit/blob/main/dooit/utils/example_config.yaml)

**Expected behavior**  🤔 
the expected behavior is to throw an error or set a default value for the missing parameter but in the case of banner or the `welcome_message` the value should be empty

**Desktop (please complete the following information):**  🤖
 - OS: Arch Linux
 - Version: 0.2.1

I can fix this issue easily with a pr but right now I don't have a time for it :(

**Comment by kraanzu** [comment]
Sorry for the inconvenience. Will fix it soon :)

**Comment by kraanzu** [comment]
Fixed in v1.0 which uses a whole new config idea!
