### ISSUE TITLE
💡 [FEAT] Time support in due date

### ISSUE THREAD

**Issue by Arjun31415** [kraanzu/dooit#66]
Option for choosing time along with due date. 
Like - 13:00 10-10-2022

Would help in managing multiple due tasks  on the same day.

**Comment by kraanzu** [comment]
Nice... Maybe I can a binding `t` just like we have `d` for changing date which will allow us to edit time in hh:mm format :)

**Comment by Arjun31415** [comment]
Is there also a way to show the overdue/late tasks in different colour/pane

**Comment by kraanzu** [comment]
No, I'm afraid not.
But you can sort the tasks according to their urgency and the overdue/late tasks will be at the top :smile:

**Comment by kraanzu** [comment]
Implemented!
