### ISSUE TITLE
typo in the first few seconds on the intro video

### ISSUE THREAD

**Issue by deven367** [kraanzu/dooit#67]
The introduction video on the `README.md` file has a typo. The video starts by typing `doit` and not `dooit`.

![image](https://user-images.githubusercontent.com/31466137/184522340-c82dd763-3480-42b3-9f96-d6ab3d983436.png)

**Comment by kraanzu** [comment]
Yeah actually the name was doit instead of dooit at first but I changed as doit was already taken by a popular software :)
I'll upload a new video soon

**Comment by deven367** [comment]
Thanks for getting back quickly! :)
