### ISSUE TITLE
💡 [FEAT] Support for for nesting of TODOs

### ISSUE THREAD

**Issue by TOMES-TT** [kraanzu/dooit#70]
**Is your feature request related to a problem? 😢 Please describe.** 
For my use case, I find that having only one layer of nesting for child todos is very limiting (ie, I often need to do tasks 1, 2, and 3 in order to accomplish task A, which itself is one of multiple tasks required to complete todo foo)

**Describe the solution you'd like**   🤔
I would like `A` to create a child under any todo, including a child todo.

**Comment by kraanzu** [comment]
Hey @TOMES-TT ,

I had a discussion on this before [here](https://github.com/kraanzu/dooit/issues/58#issuecomment-1179636554)

The point about code complications seems vague now.
 It was just bad design decisions that I plan to work on soon.

However, the first point still remains valid
I tried nesting too much which made the date column something like this:

The upper/parent tasks' date rendered ideally as they were supposed to be  
But in the nested regions the letters got separated into different lines creating something like this:

```
No
 Due
Date
```
Idea :bulb::
What I can do now is to allow the users to tweak the UI and provide the respected ratios they want to assign to each column and the number of columns they want to see (for e.g. they don't want the urgency column they can remove that)

Example config:
```python
tasks: 70
date: 20
urgency: 10
```

Where the number shows the ratio to divide the columns into ( according to the terminal's width ) where 0 means don't show the column

What are your thoughts on this?

**Comment by TOMES-TT** [comment]
Hi,

Thanks for the response! My mistake for not realizing there was already discussion on this topic, I thought I had checked everywhere but I'm still pretty new to github so I must have missed it. I think that would be a good solution.

**Comment by kraanzu** [comment]
> My mistake for not realizing there was already discussion on this topic

No problemo!

> I think that would be a good solution.

I'm a bit busy with my work and am not getting too much time for github stuff, so might be a while :disappointed: .
I'll keep this thread open and will update once implemented

**Comment by TOMES-TT** [comment]
Yeah, no worries; obviously I'm just requesting stuff from you, so I have no expectations about it :)
Something that just occurred to me; due dates could be made optional, which would let the todo column stretch out to basically fill the entire terminal window

**Comment by kraanzu** [comment]
> Something that just occurred to me; due dates could be made optional, which would let the todo column stretch out to basically fill the entire terminal window

Yes, I did mention that:
> where 0 means don't show the column

**Comment by kraanzu** [comment]
I am also thinking to make the Workspace or the left section toggleable (with animation).
The current code wouldn't allow that but I'll implement it soon.

**Comment by kraanzu** [comment]
Implemented in v1.0
