### ISSUE TITLE
💡 [FEAT] Parse human-readable due dates

### ISSUE THREAD

**Issue by ehawman** [kraanzu/dooit#71]
**Is your feature request related to a problem? 😢 Please describe.** 
dd-mm-yyyy is understandable, but somewhat clunky. It also requires that you look up or calculate dates yourself ("What is next Friday's date again?")

**Describe the solution you'd like**   🤔
[Implement the dateparser library.](https://dateparser.readthedocs.io/en/latest/) It parses human-readable date strings into python datetime objects.

**Describe alternatives you've considered**  🧐
Gitting gud @ dates 😜 

**Additional context** 📝

**Comment by kraanzu** [comment]
Hi @ehawman, 
This looks super awesome! Thanks for sharing it!
I'll create a new release soon. Will add it to that <3

**Comment by kraanzu** [comment]
Implemented!
