### ISSUE TITLE
💡 [FEAT] Approximate Task Duration

### ISSUE THREAD

**Issue by FelixKratz** [kraanzu/dooit#74]
I really like this tool, it makes planning todos so much more fun. Thank you for creating it!
One thing that I would really enjoy is to have an approximate task duration field where I could enter how long I think the task will take to accomplish. E.g. if I look for a task that takes ~1h I could find them more quickly and work on them when I have a time constraint.

A next step for such feature could be support to "pick" tasks for the day. Once a task is picked for the day its due date is changed to today and added to a "Today" view, along with the estimate duration of the task.

**Comment by kraanzu** [comment]
>if I look for a task that takes ~1h I could find them more quickly and work on them when I have a time constraint. 

I guess you mean a task timer something similar to taskwarrior.
I'll explain the workflow and you can give me feedback for this:
- You  go to the task and let's say press `s` for `start`
- You are prompted to enter a duration for e.g. `50s` or `50m`  or `50h`
- A timer starts and notifies you when the time is up ( If the task is not done by then else just stops)
If not done, It can maybe add some extra time ( let' say 10% of the initial time) and notifies you again. Something like a alarm snooze

> A next step for such feature could be support to "pick" tasks for the day. Once a task is picked for the day its due date is changed to today and added to a "Today" view

Hmm..that can be a nice feature to add. Thanks for recommending
I'll release a new version soon and will be sure to add these 😄 


> I really like this tool, it makes planning todos so much more fun. Thank you for creating it!

Thank you so much. I really appreciate it <3

**Comment by FelixKratz** [comment]
> I guess you mean a task timer something similar to taskwarrior. I'll explain the workflow and you can give me feedback for this
What you describe is different from what I had in mind, but it sure is nice too.

What I thought was an "Approximate Duration" field for a task that can be filled at any time and is displayed next to the due date (or anywhere else). I find myself creating tasks for which I know approximately how long they will take when I create them.

E.g.:
* I create an item: Refactor Code
* I fill the estimate duration of the task: e.g. 2 hours
* I work on different tasks
* When I have ~2 hours of time I search for tasks that can be completed in this time
* I am able to easily find the *Refactor Code* task and start it

Once I start the task your idea with the timer would directly attach onto this workflow.

**Comment by kraanzu** [comment]
Ah, I see now. That surely will be nice! We can attach more functionalities later on but for now the basic idea of `estimated duration` will be easy to implement.

I'm planning on adding a config option so that the user can determine the UI.
To be specific: How the rows will be rendered (both the size and position) 
For e.g. if somebody does not need an `urgency` column but the `estimated duration` column, that would be possible to tweak through the config.

What are your thoughts on it?

**Comment by FelixKratz** [comment]
> Ah, I see now. That surely will be nice! We can attach more functionalities later on but for now the basic idea of `estimated duration` will be easy to implement.
> 
> I'm planning on adding a config option so that the user can determine the UI. To be specific: How the rows will be rendered (both the size and position) For e.g. if somebody does not need an `urgency` column but the `estimated duration` column, that would be possible to tweak through the config.
> 
> What are your thoughts on it?

Making this configurable sounds great! Thank you for your work on this project.

**Comment by kraanzu** [comment]
Awesome then!

**Comment by kraanzu** [comment]
Hi @FelixKratz,
Woah I'm really late on this one haha. Was really busy with some other work :p
but I've implemented an "Effort" parameter which is just a number and you can use it like the hour thing you mentioned
