### ISSUE TITLE
💡 [FEAT] Ability to yank and paste entire todo's

### ISSUE THREAD

**Issue by atidyshirt** [kraanzu/dooit#76]
**Is your feature request related to a problem? 😢 Please describe.** 

I would like the ability to copy and paste entire todo's between topics, and have the ability to copy multiple todo's.

**Describe the solution you'd like**   🤔

I would like to have a solution that does the following:

1. `Y` to yank entire todo's
2. `Y` if triggered on a parent todo, should copy all child todo's to the clipboard
3. `p` or `P` to paste a todo that has been copied
4. Ideally, If a child node has been copied, it can be made a parent or child todo depending on where it is pasted
5. A parent node can only be pasted as a parent todo

**Describe alternatives you've considered**  🧐

An extension of this idea would be to use `D` to delete and copy the selected todo, and of course I am open to alternative default bindings.

**Additional context** 📝

I don't know how hard this is to implement as I have only recently started using the app and am loving it so far.

When I have some available time I will take a look at the code and if this is something you would like to include, I would be happy to help.

**Comment by kraanzu** [comment]
Hi @atidyshirt! Thanks for the feature idea!

I was actually wondering how to make such a feature to move the todos within the app! This sounds good and can be a great implementation!

> I don't know how hard this is to implement as I have only recently started using the app and am loving it so far.

Thanks, bud! I really appreciate it :smile: 

> When I have some available time I will take a look at the code and if this is something you would like to include, I would be happy to help.

Of course, I am also willing to help if you need any :smile: 
I saw that you forked the project a couple of hours ago. Just wanted you to know that you should ignore the main branch and have a look at the *redesign* branch as the implementation is kinda totally different :sweat_smile: 
That'll make it easier to implement stuff :smiley:

**Comment by atidyshirt** [comment]
Hi @kraanzu, Oh I have been working on this using the main branch, thanks for letting me know :)

I will switch branches and take a look at how to bring my implementation across. (I have never used rich or TUI interfaces in python before, but starting to understand the code now).

Hopefully I will be back with a PR soon

**Comment by kraanzu** [comment]
Awesoome! Good luck :)

Here's the documention for textual if you need any help:
https://textual.textualize.io/

**Comment by kraanzu** [comment]
Haha...thought so! But I there aren't many now :(
Ummm... If you can maybe wait for one more day? I guess I'll finish it up ( there will be bugs surely but I'll try to solve most of them by sunday? )

this is the test file I use which should run the app:
```python
from dooit.__init__ import main
main()
```

Can I ask what Kind of issues are you facing? Have you upgraded textual's version?

**Comment by atidyshirt** [comment]
I think I may have introduced one, not sure. I have experienced occasional freezing and sometimes `TODO`'s get removed if we do things too quickly (I think some async issue).

Do not feel pressured at all, that was not my intention 😄 ,  just curios if there was any known issues.

Might also be note worthy that I am currently on a ARM Macbook

**Comment by atidyshirt** [comment]
Thats all I have in me tonight! Couple of notes on this:

If you can think of a better method to handle the clipboard management then the implemented method, I am all ears (i.e the following):

```python
@dataclass
class S_Storage:
    instance = None
    def __init__(self):
        S_Storage.instance = self
        self._clipboard = None

class Storage:
    clipboard = S_Storage.instance._clipboard if S_Storage.instance else S_Storage()._clipboard
```

There is still a couple of things to fix in here, will submit a PR when this is ready

**Comment by kraanzu** [comment]
Awesome! This looks good. Thanks for the PR

> There is still a couple of things to fix in here, will submit a PR when this is ready

Yep Yep. I'll work on it too and hopefully remove some bugs along the way :)

**Comment by kraanzu** [comment]
> Cannot quit using ctrl + q
Done!

> Cannot use escape to exit the help menu
Fixed!

> Freezing (seems to be when doing things quickly)
I've implemented lazy load. Can you check if it's still freezing for ya?

**Comment by atidyshirt** [comment]
I will retest tomorrow and see if what problems are present, pasting todos is now functional, 'P' go paste as child, 'p' to paste as sibling, and todo's are copied using the 'remove' method ('x') (removed and copied node to the clipboard).

I have a couple of questions about copying todo's, I have noticed that we cannot have two todos with the same description at the same level? So as far as implementing copy, I guess we want to achieve the following implementation:

* Copy a Todo to clipboard
* Extend pasting method to do as follows
** Pasting will only paste node if `List[TreeNode]` does not contain the existing node

Is this the expected bahaviour? Or any other ideas?

**Comment by kraanzu** [comment]
> I have noticed that we cannot have two todos with the same description at the same level? 

Yes, that is correct! That makes some implementation stuff easier (when the todos are changed in some other instance or changed through some plugins)
The only case I see where you need the same todo description is to do some recurring tasks such as:

- Solve a problem every day
- Get a haircut every 6 weeks

For that, I've implemented recurring tasks which when marked as completed just shift their date accordingly

> Possibly implemented with 'y' for copying the node and only description with 'Y' would be my personal preference

I suppose we can include some of the special keybindings in the configuration file to tweak as per the user's preference
I was also thinking to implement multi-key presses as we have in vim (if you are familiar) such as `<space>p` and `dd` but that would require some good implementation. We can do that tho!
