### ISSUE TITLE
💡 [FEAT] Building website for dooit

### ISSUE THREAD

**Issue by kyeboard** [kraanzu/dooit#77]
**Is your feature request related to a problem? Please describe.** 
Maybe (hadn't checked other issues)

**Describe the solution you'd like**   🤔
Build an blazingly beautiful website for dooit. It is gonna be mostly containing the home page showing up all the awesome features, installation (not really anything in installation, what's hard in adding, aye?), marketplace that is gonna contain a bunch of plugins.

**Describe alternatives you've considered**  🧐
No other alternatives

**Additional context** 📝
Let me know if there is any other thing that you want me to add, would be glad to do so. I would finish up the work within this week, I hope.

Assign me :D

**Comment by kraanzu** [comment]
Aight!
