### ISSUE TITLE
Compatability with modern (>=0.6.0) textual

### ISSUE THREAD

**Issue by JamiKettunen** [kraanzu/dooit#81]
Hey! I was packaging this neat TUI program for Void Linux, but as a part of that noticed https://github.com/Textualize/textual wasn't yet part of the repo, so obviously I grabbed [the latest v0.9.1](https://github.com/Textualize/textual/releases/tag/v0.9.1) for the package, and surprise `dooit` isn't happy with that:
```
$ dooit --help
Traceback (most recent call last):
  File "/bin/dooit", line 5, in <module>
    from dooit.__init__ import main
  File "/usr/lib/python3.11/site-packages/dooit/__init__.py", line 4, in <module>
    from .ui.tui import Doit
  File "/usr/lib/python3.11/site-packages/dooit/ui/tui.py", line 2, in <module>
    from ..utils.parser import Parser
  File "/usr/lib/python3.11/site-packages/dooit/utils/__init__.py", line 1, in <module>
    from .parser import Parser
  File "/usr/lib/python3.11/site-packages/dooit/utils/parser.py", line 6, in <module>
    from ..ui.widgets import Entry, Navbar, SimpleInput, TodoList
  File "/usr/lib/python3.11/site-packages/dooit/ui/widgets/__init__.py", line 1, in <module>
    from .nested_list_edit import NestedListEdit
  File "/usr/lib/python3.11/site-packages/dooit/ui/widgets/nested_list_edit.py", line 6, in <module>
    from textual.widgets import TreeControl, TreeNode, NodeID
  File "/usr/lib/python3.11/site-packages/textual/widgets/__init__.py", line 62, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'TreeControl'
```
In https://raw.githubusercontent.com/Textualize/textual/main/CHANGELOG.md I found:
```
## [0.6.0] - 2022-12-11

### Added

...
- Added `Tree` widget which replaces `TreeControl`.
```
I also tried latest git commit of `dooit` (currently https://github.com/kraanzu/dooit/commit/fb11030dc9b213a336730bb1fbaf2a8922ab6d02) but to no avail.

It would be great if this program was updated to work with the latest version of `textual` ^^

**Comment by kraanzu** [comment]
Hey there! 
Yes, the current version of dooit uses an old version of textual. 
A lot was changed in its v2.0 as you can see [here](https://github.com/Textualize/textual/releases/tag/v0.2.0)
So dooit needed a total makeover which I'm working on currently on the `redesign` branch which introduces new features along with the latest version of textual and I'm almost done with it. 
I'll keep this thread open and will notify as soon it merges into the main branch :D

**Comment by JamiKettunen** [comment]
Thanks for the fast response! Indeed the [`redesign` branch](https://github.com/kraanzu/dooit/tree/redesign) works with at least `textual` [v0.7.0](https://github.com/Textualize/textual/releases/tag/v0.7.0); I tracked key input breaking (any key input quits the program immediately) down to [v0.8.0](https://github.com/Textualize/textual/releases/tag/v0.8.0) fwiw, and I even managed to capture this once (with v0.9.1):
![image](https://user-images.githubusercontent.com/47358222/210595442-c3b42d92-3c7b-442e-a679-8cfd0bd804ef.png)


 I'm happy with this for now and can at least use it locally ^^

**Comment by kraanzu** [comment]
Hmm...more changes eh!  Thanks for checking @JamiKettunen, I'll look into it and push a fix :D

**Comment by JamiKettunen** [comment]
Not exactly relevant to textual version, but would it be possible to get some visual indication that a workspace has some collapsed children (`z`)? I also feel like especially workspace deletions should have a confirm dialog of some form always so you don't accidentally nuke it all.

Btw I got this to happen by adding a workspace removing it and trying to add one quickly afterwards
![image](https://user-images.githubusercontent.com/47358222/210653649-5f8b688e-5b62-4ba7-85ca-2285329e6bf7.png)

Additionally I noticed sometimes adding a workspace (`a`), then cancelling (`esc`) and adding a child workspace (`A`) all in quick succession gets it to stop editing the new child workspace name and starts editing the parent's one presumably after the `Checking for modifications...` timer runs out in a second or so

**Comment by JamiKettunen** [comment]
`Shift` + `Tab` should also switch between the workspace and todo views, perhaps also `Left` and `Right` arrow keys too (at least in main view?), though those could conflict with some other existing functionality maybe

**Comment by JamiKettunen** [comment]
Hm also can't paste anything from my clipboard into the todo items, rather annoying imho

**Comment by JamiKettunen** [comment]
I'm not a big fan of this whole timer design, I can't do some things fast enough and it gets in the way, for example if I add a todo with `a` and then quickly after I press `enter` I add a subtask with `A`, it can just say `Can't leave description empty!` even though I literally just filled it in for the parent, and then it starts editing the text of the parent and removes the subitem I was going to work on.

Can I just file these as regular issues even though they target [the `redesign` branch](https://github.com/kraanzu/dooit/tree/redesign)? I don't want to keep spamming more irrelevant comments here :p

**Comment by kraanzu** [comment]
> Shift + Tab should also switch between the workspace and todo views (similar to Tab alone), ......

Yes, that's in my to-do list... I've still gotta take care of these small stuff after I'm done with main logic implementation :D

**Comment by JamiKettunen** [comment]
I managed to accidentally press `x` on one of my workspaces with many subitems, now they're all gone in the aether. welp. I'm requesting a confirm dialog for deletion (I guess with ability to restore current behavior in config)

**Comment by kraanzu** [comment]
Hmmm... Not sure about a dialogue. But I can show a prompt saying:
-----

Deleting a `todo/branched todo`!  Press `x` again to delete

This behaviour could be changed in the config:

```python
CONFIRM_BEFORE_DELETE = True
```

**Comment by JamiKettunen** [comment]
Sounds much better. Btw now I managed to make the whole program freeze by pressing `A` on the last (3rd) todo item on a workspace soon after creating a new one

**Comment by kraanzu** [comment]
> I managed to make the whole program freeze by pressing A on the last (3rd) todo item soon after creating the 3rd todo item on a workspace

Hmmm... I managed to do that on making third nesting but then tried again and everything went smoothly. Not really sure how to pin down the issue. My best guess is that it's happening during read/write updates. I'll dig more into it

**Comment by JamiKettunen** [comment]
Hm any chance we could get ability to move child items (workspaces) around in the menu? I added some sub-workspaces under the wrong one and now can't move them under the right one without removing and adding everything again
![image](https://user-images.githubusercontent.com/47358222/210886791-f4b85084-6313-46ad-bf45-2613ddd09ca4.png)
![image](https://user-images.githubusercontent.com/47358222/210886736-c29a2f21-ff8c-456b-98d9-08cf0c0b91bc.png)

**Comment by kraanzu** [comment]
Ah yes, Ther's also a PR on this ( #78 )
Not really sure if the developer is working on it rn or not... But yeah, the  implementation is pretty easy :D

**Comment by kraanzu** [comment]
Merged!
