### ISSUE TITLE
[BUG] tried to install it + one random nerdfont but no icons

### ISSUE THREAD

**Issue by BarbzYHOOL** [kraanzu/dooit#83]
**Describe the bug** 🐛
 tried to install it + one random nerdfont but no icons
I took the "agave" nerd fonts and put it in ~/.local/share/fonts but it didn't change anything

**Expected behavior**  🤔 
It should automatically install a correct font by asking the user first, or tell the user to configure his own font.

**Desktop (please complete the following information):**  🤖
 - OS: pop os 22.04

**Additional context** 📝
At least, explain how to install the font in the readme plz

**Comment by kraanzu** [comment]
> I took the "agave" nerd fonts and put it in ~/.local/share/fonts but it didn't change anything


And then did you ran `fc-cache -fv` ?
And you changed the font in the terminal settings right?
**Also: You can put it in `~/.fonts` too. That'd be a lot better :)**

>  At least, explain how to install the font in the readme plz

Hmm...I can link a post or something explaining how to install them
It turned out to be a problem for many people so I'll be only using Unicode in the next release :D

**Comment by BarbzYHOOL** [comment]
> And then did you ran fc-cache -fv ?
> And you changed the font in the terminal settings right?

No and no :P i think the most important thing is to change it in the terminal settings but I didn't realize (i was on a live iso lol). On my current terminal I have Jetbrains font though, I would like to keep it I guess

**Comment by kraanzu** [comment]
I see :D

**Comment by BarbzYHOOL** [comment]
Eh, I tried dooit again with "pipx run" (not installed)
and (except that i'm lost with the controls) the icons are not showing again

Is it normal to look like this?

![image](https://github.com/kraanzu/dooit/assets/29780637/64965c17-d2f3-485f-bced-9551fe5cf437)

**Comment by kraanzu** [comment]
Heyy! Yes, I changed the icons to regular characters because a lot of people were facing issues with the nerd font :)
You can still change them in the config tho
see [wiki](https://github.com/kraanzu/dooit/wiki/Configuration#todos)

**Comment by BarbzYHOOL** [comment]
> Heyy! Yes, I changed the icons to regular characters because a lot of people were facing issues with the nerd font :) You can still change them in the config tho see [wiki](https://github.com/kraanzu/dooit/wiki/Configuration#todos)

so this pic in the readme should be changed, no?
https://user-images.githubusercontent.com/97718086/264970969-55d37e59-e651-45e7-9c8d-4321e566b655.png

**Comment by kraanzu** [comment]
I think I can add a wiki section to get the exact copy of the custom configuration.
The image shows the configuration options so I think I shouldn't remove it from the README
So yeah, I'll update the wiki and mention the change here

**Comment by BarbzYHOOL** [comment]
we can have it look like this??
But only with configuring?

**Comment by kraanzu** [comment]
Yes! It's only changing some default icons

**Comment by BarbzYHOOL** [comment]
give it to me!

**Comment by kraanzu** [comment]
Here's the whole folder: https://github.com/kraanzu/.dotfiles/tree/main/configs/dooit

**Comment by BarbzYHOOL** [comment]
where is the config directory? i cannot run your command as I installed with pipx run

**Comment by kraanzu** [comment]
You can find the config dir by running this is the shell:

```bash
python -c "import appdirs; print(appdirs.user_config_dir('dooit'))"
```
