### ISSUE TITLE
[BUG] Creating a menu item with '/' breaks the application

### ISSUE THREAD

**Issue by rish106** [kraanzu/dooit#84]
**Describe the bug** 🐛
The application completely breaks when one creates/renames a menu item to a string containing the '/' character.

**To Reproduce** 🐣
1. Create a menu item with the '/' character.
2. See error

**Expected behavior**  🤔 
There should be no errors when creating a menu item with the '/' character.

**Screenshots** 🧐
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/36294070/211219191-426452f9-5541-41ed-86cc-a395d9f6df42.png">

**Desktop (please complete the following information):**  🤖
 - OS: macOS
 - Version: Ventura 13.1

**Comment by kraanzu** [comment]
Hmm. Bad choice to use a delimiter of length 1. I will fix this in next update :D

**Comment by kraanzu** [comment]
Fixed in v.1.0.0
