### ISSUE TITLE
[BUG] Can't add Sub-Subnode

### ISSUE THREAD

**Issue by yuckdevchan** [kraanzu/dooit#85]
**Describe the bug** 🐛
When I try to add a subnode (shift+a) to a subnode it doesn't work - I can only add subnodes to normal nodes

**To Reproduce** 🐣
1. Create a Node
2. Create a Subnode on that node
3. Create a Subnode on that Subnode from Step 2
4. Nothing Happens?

**Expected behavior**  🤔 
Another subnode to be created

**Desktop (please complete the following information):**  🤖
 - OS: SteamOS with RWFS and i3
 - Version: 3.4

**Comment by kraanzu** [comment]
Hi there @yuckdevchan!
It's not a bug... I implemented it that way for some reason but I'm working on a new version that does not have this restriction. Will close this issue once released :D

**Comment by yuckdevchan** [comment]
> Hi there @yuckdevchan! It's not a bug... I implemented it that way for some reason but I'm working on a new version that does not have this restriction. Will close this issue once released :D

OK, Thanks - Good to know this feature is coming. 👍

**Comment by kraanzu** [comment]
Implemented in v1.0

**Comment by yuckdevchan** [comment]
> Implemented in v1.0

Thanks a million!

**Comment by kraanzu** [comment]
Thanks a million for all the love and support <3
