### ISSUE TITLE
Character drawing generation [Question]

### ISSUE THREAD

**Issue by Coder-Liuu** [kraanzu/dooit#89]
Hey buddy, your work is really great! I'm learning to build TUI programs, and I found that your work has a nice character painting, as shown below.

![](https://user-images.githubusercontent.com/97718086/221467485-fae198f7-51b1-4a71-91d9-88b51897aeeb.png)
But when I searched for "Can you complete your tasks today?" in the code repository, I didn't find anything, can you tell me how the character drawing is generated.

**Comment by kraanzu** [comment]
Hi @Coder-Liuu, Indeed I did not put it in the repo because I thought It'd be too much bloat!
It's my custom config, you can work the artwork file [here](https://github.com/kraanzu/.dotfiles/blob/main/dooit/.config/dooit/utils/ascii.py)

**Comment by Coder-Liuu** [comment]
Thank you for letting me know, @kraanzu ! I appreciate your help. I will use this idea to add character drawing to my TUI program.

BTW, the TUI program you made is really awesome. :blush:

**Comment by kraanzu** [comment]
I'm glad that I was of help! Best of luck to you!
