### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by crymer** [kraanzu/dooit#91]
**Describe the bug** 🐛
I installed dooit on Windows via "pip install dooit". I attempted to start dooit via Windows terminal and a terminal emulator and received the following error in both. I also attempted to install dooit in a venv and received the same error. 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\XXX\\AppData\\Local\\dooit\\dooit'

Dooit package was installed on my computer in Python/site-packages/dooit

Dooit.exe was installed in Python/Python310/Scripts

Is Dooit expected to run on Windows with Python 3.10?

**Comment by crymer** [comment]
Nice work @kraanzu !!! Thanks so much. Looking forward to using your program!

**Comment by kraanzu** [comment]
Thanks! Feel free to share any feedbacks :D
