### ISSUE TITLE
💡 [FEAT] Ability to filter by tags

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#94]
Tags UI is great. However, when I tried to filter by tags. It doesn't seem possible. I tried searching for tags too, It didn't seem to work.

while searching. Just an ui like `/tag tag1 tag2 tag3` will be great and will be intuitive.

**Comment by kraanzu** [comment]
Yes that will be implemented in a future version! I released a bit early in order to close most of the issues :smile: 
Should be pretty smile

Like if you were to search for a todo that contains the work `todo` with the tag `imp` then you could probably look it up using this query:

```
/todo t:imp
```

**Comment by sathishmanohar** [comment]
It is often great to release early and gain feedback from real users. I've tried a number of tui todo apps and I found dooit to be the most intuitive one.

I would like add the importance of filtering with multiple tags as well. Like

`/todo t:imp,email`
`/frontend t:blocker,js`

etc.

**Comment by kraanzu** [comment]
> I would like add the importance of filtering with multiple tags as well.

Yes Yes, that should work!

> I've tried a number of tui todo apps and I found dooit to be the most intuitive one.

I'm really happy to hear that!

**Comment by kraanzu** [comment]
Closing as now you can search with `@<tag>`
