### ISSUE TITLE
💡 [FEAT] Support h / l to switch between panes

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#96]
Currently only tab key seems to be supported. Even shift+tab didn't work when I tried to go back to the previous pane.

Since dooit is going for vim like keybindings, I think using h and l keys to switch focus to previous and next panes would be a lot more intuitive.

**Comment by kraanzu** [comment]
Ah yes, you can change that in the config file

It should be present at `~/.config/dooit/config.py`

Since there are only two tabs, I only kept one keybind to toggle between the panes
You can configure the keys in the config file
[here's](https://github.com/kraanzu/dooit/wiki/Key-Bindings) an example

**Comment by sathishmanohar** [comment]
Got it. Looks like there is currently support for one command to switch panes which is `switch pane` so the h / l approach can't be done in config files. Maybe when `next pane` and `previous pane` are implemented. This issue can be revisited.

**Comment by kraanzu** [comment]
Alright, I'll add those!

**Comment by sathishmanohar** [comment]
Awesome!

`h` or `<shift+tab>` for `previous pane`
`l` or `<tab>` for `next pane`

would be a great default biding. These bindings can scale if there is third pane implemented in the future for notes or other things.

**Comment by Justinzobel** [comment]
I'd love to see the left and right arrow keys work as well. I can't get used to checking which pane is highlighted before using my arrow keys to navigate up/down.

**Comment by sathishmanohar** [comment]
@Justinzobel I've sometimes felt the active pane border color is sometimes confusing because it is a muted color. If that is what you mean. I think it should be a separate issue.

**Comment by kraanzu** [comment]
Fixed in new release
